namespace :load_animals do
  desc 'load animal names'
  task initialize: :environment do
    Animal.create(search_name: 'Aardvark', image_name: 'Aardvark', real: 'Real')
    Animal.create(search_name: 'Abyssinian', image_name: 'Abyssinian', real: 'Real')
    Animal.create(search_name: 'Adelie Penguin', image_name: 'Adelie-Penguin', real: 'Real')
    Animal.create(search_name: 'Affenpinscher', image_name: 'Affenpinscher', real: 'Real')
    Animal.create(search_name: 'Afghan Hound', image_name: 'Afghan-Hound', real: 'Real')
    Animal.create(search_name: 'African Bush Elephant', image_name: 'African-Bush-Elephant', real: 'Real')
    Animal.create(search_name: 'African Civet', image_name: 'African-Civet', real: 'Real')
    Animal.create(search_name: 'African Clawed Frog', image_name: 'African-Clawed-Frog', real: 'Real')
    Animal.create(search_name: 'African Forest Elephant', image_name: 'African-Forest-Elephant', real: 'Real')
    Animal.create(search_name: 'African Palm Civet', image_name: 'African-Palm-Civet', real: 'Real')
    Animal.create(search_name: 'African Penguin', image_name: 'African-Penguin', real: 'Real')
    Animal.create(search_name: 'African Tree Frog', image_name: 'African-Tree-Frog', real: 'Real')
    Animal.create(search_name: 'African Wild Dog', image_name: 'African-Wild-Dog', real: 'Real')
    Animal.create(search_name: 'Ainu Dog', image_name: 'Ainu-Dog', real: 'Real')
    Animal.create(search_name: 'Airedale Terrier', image_name: 'Airedale-Terrier', real: 'Real')
    Animal.create(search_name: 'Akbash', image_name: 'Akbash', real: 'Real')
    Animal.create(search_name: 'Akita', image_name: 'Akita', real: 'Real')
    Animal.create(search_name: 'Alaskan Malamute', image_name: 'Alaskan-Malamute', real: 'Real')
    Animal.create(search_name: 'Albatross', image_name: 'Albatross', real: 'Real')
    Animal.create(search_name: 'Aldabra Giant Tortoise', image_name: 'Aldabra-Giant-Tortoise', real: 'Real')
    Animal.create(search_name: 'Alligator', image_name: 'Alligator', real: 'Real')
    Animal.create(search_name: 'Alpaca', image_name: 'Alpaca', real: 'Real')
    Animal.create(search_name: 'Alpine Dachsbracke', image_name: 'Alpine-Dachsbracke', real: 'Real')
    Animal.create(search_name: 'Amazon River Dolphin', image_name: 'Amazon-River-Dolphin', real: 'Real')
    Animal.create(search_name: 'American Alsatian', image_name: 'American-Alsatian', real: 'Real')
    Animal.create(search_name: 'American Bulldog', image_name: 'American-Bulldog', real: 'Real')
    Animal.create(search_name: 'American Cocker Spaniel', image_name: 'American-Cocker-Spaniel', real: 'Real')
    Animal.create(search_name: 'American Coonhound', image_name: 'American-Coonhound', real: 'Real')
    Animal.create(search_name: 'American Eskimo Dog', image_name: 'American-Eskimo-Dog', real: 'Real')
    Animal.create(search_name: 'American Foxhound', image_name: 'American-Foxhound', real: 'Real')
    Animal.create(search_name: 'American Pit Bull Terrier', image_name: 'American-Pit-Bull-Terrier', real: 'Real')
    Animal.create(search_name: 'American Staffordshire Terrier', image_name: 'American-Staffordshire-Terrier', real: 'Real')
    Animal.create(search_name: 'American Water Spaniel', image_name: 'American-Water-Spaniel', real: 'Real')
    Animal.create(search_name: 'Amur Leopard', image_name: 'Amur-Leopard', real: 'Real')
    Animal.create(search_name: 'Anatolian Shepherd Dog', image_name: 'Anatolian-Shepherd-Dog', real: 'Real')
    Animal.create(search_name: 'Angelfish', image_name: 'Angelfish', real: 'Real')
    Animal.create(search_name: 'Ant', image_name: 'Ant', real: 'Real')
    Animal.create(search_name: 'Anteater', image_name: 'Anteater', real: 'Real')
    Animal.create(search_name: 'Antelope', image_name: 'Antelope', real: 'Real')
    Animal.create(search_name: 'Appenzeller Dog', image_name: 'Appenzeller-Dog', real: 'Real')
    Animal.create(search_name: 'Arctic Fox', image_name: 'Arctic-Fox', real: 'Real')
    Animal.create(search_name: 'Arctic Hare', image_name: 'Arctic-Hare', real: 'Real')
    Animal.create(search_name: 'Arctic Wolf', image_name: 'Arctic-Wolf', real: 'Real')
    Animal.create(search_name: 'Armadillo', image_name: 'Armadillo', real: 'Real')
    Animal.create(search_name: 'Asian Elephant', image_name: 'Asian-Elephant', real: 'Real')
    Animal.create(search_name: 'Asian Giant Hornet', image_name: 'Asian-Giant-Hornet', real: 'Real')
    Animal.create(search_name: 'Asian Palm Civet', image_name: 'Asian-Palm-Civet', real: 'Real')
    Animal.create(search_name: 'Asiatic Black Bear', image_name: 'Asiatic-Black-Bear', real: 'Real')
    Animal.create(search_name: 'Aurochs', image_name: 'Aurochs', real: 'Real')
    Animal.create(search_name: 'Australian Cattle Dog', image_name: 'Australian-Cattle-Dog', real: 'Real')
    Animal.create(search_name: 'Australian Kelpie Dog', image_name: 'Australian-Kelpie-Dog', real: 'Real')
    Animal.create(search_name: 'Australian Mist', image_name: 'Australian-Mist', real: 'Real')
    Animal.create(search_name: 'Australian Shepherd', image_name: 'Australian-Shepherd', real: 'Real')
    Animal.create(search_name: 'Australian Terrier', image_name: 'Australian-Terrier', real: 'Real')
    Animal.create(search_name: 'Avocet', image_name: 'Avocet', real: 'Real')
    Animal.create(search_name: 'Axolotl', image_name: 'Axolotl', real: 'Real')
    Animal.create(search_name: 'Aye Aye', image_name: 'Aye-Aye', real: 'Real')
    Animal.create(search_name: 'Baboon', image_name: 'Baboon', real: 'Real')
    Animal.create(search_name: 'Bactrian Camel', image_name: 'Bactrian-Camel', real: 'Real')
    Animal.create(search_name: 'Badger', image_name: 'Badger', real: 'Real')
    Animal.create(search_name: 'Baiji', image_name: 'Baiji', real: 'Real')
    Animal.create(search_name: 'Balinese', image_name: 'Balinese', real: 'Real')
    Animal.create(search_name: 'Banded Palm Civet', image_name: 'Banded-Palm-Civet', real: 'Real')
    Animal.create(search_name: 'Bandicoot', image_name: 'Bandicoot', real: 'Real')
    Animal.create(search_name: 'Barb', image_name: 'Barb', real: 'Real')
    Animal.create(search_name: 'Barn Owl', image_name: 'Barn-Owl', real: 'Real')
    Animal.create(search_name: 'Barnacle', image_name: 'Barnacle', real: 'Real')
    Animal.create(search_name: 'Barracuda', image_name: 'Barracuda', real: 'Real')
    Animal.create(search_name: 'Barramundi Fish', image_name: 'Barramundi-Fish', real: 'Real')
    Animal.create(search_name: 'Basenji Dog', image_name: 'Basenji-Dog', real: 'Real')
    Animal.create(search_name: 'Basking Shark', image_name: 'Basking-Shark', real: 'Real')
    Animal.create(search_name: 'Basset Fauve de Bretagne', image_name: 'Basset-Fauve-de-Bretagne', real: 'Real')
    Animal.create(search_name: 'Basset Hound', image_name: 'Basset-Hound', real: 'Real')
    Animal.create(search_name: 'Bat', image_name: 'Bat', real: 'Real')
    Animal.create(search_name: 'Bavarian Mountain Hound', image_name: 'Bavarian-Mountain-Hound', real: 'Real')
    Animal.create(search_name: 'Beagle', image_name: 'Beagle', real: 'Real')
    Animal.create(search_name: 'Bear', image_name: 'Bear', real: 'Real')
    Animal.create(search_name: 'Bearded Collie', image_name: 'Bearded-Collie', real: 'Real')
    Animal.create(search_name: 'Bearded Dragon', image_name: 'Bearded-Dragon', real: 'Real')
    Animal.create(search_name: 'Beaver', image_name: 'Beaver', real: 'Real')
    Animal.create(search_name: 'Bedlington Terrier', image_name: 'Bedlington-Terrier', real: 'Real')
    Animal.create(search_name: 'Beetle', image_name: 'Beetle', real: 'Real')
    Animal.create(search_name: 'Beluga Sturgeon', image_name: 'Beluga-Sturgeon', real: 'Real')
    Animal.create(search_name: 'Bengal Tiger', image_name: 'Bengal-Tiger', real: 'Real')
    Animal.create(search_name: 'Bernese Mountain Dog', image_name: 'Bernese-Mountain-Dog', real: 'Real')
    Animal.create(search_name: 'Bichon Frise', image_name: 'Bichon-Frise', real: 'Real')
    Animal.create(search_name: 'Binturong', image_name: 'Binturong', real: 'Real')
    Animal.create(search_name: 'Bird', image_name: 'Bird', real: 'Real')
    Animal.create(search_name: 'Birds Of Paradise', image_name: 'Birds-Of-Paradise', real: 'Real')
    Animal.create(search_name: 'Birman', image_name: 'Birman', real: 'Real')
    Animal.create(search_name: 'Bison', image_name: 'Bison', real: 'Real')
    Animal.create(search_name: 'Black Marlin', image_name: 'Black-Marlin', real: 'Real')
    Animal.create(search_name: 'Black Rhinocerous', image_name: 'Black-Rhinocerous', real: 'Real')
    Animal.create(search_name: 'Black Russian Terrier', image_name: 'Black-Russian-Terrier', real: 'Real')
    Animal.create(search_name: 'Black Widow Spider', image_name: 'Black-Widow-Spider', real: 'Real')
    Animal.create(search_name: 'Blobfish', image_name: 'Blobfish', real: 'Real')
    Animal.create(search_name: 'Bloodhound', image_name: 'Bloodhound', real: 'Real')
    Animal.create(search_name: 'Blue Jay', image_name: 'Blue-Jay', real: 'Real')
    Animal.create(search_name: 'Blue Lacy Dog', image_name: 'Blue-Lacy-Dog', real: 'Real')
    Animal.create(search_name: 'Blue Whale', image_name: 'Blue-Whale', real: 'Real')
    Animal.create(search_name: 'Bluetick Coonhound', image_name: 'Bluetick-Coonhound', real: 'Real')
    Animal.create(search_name: 'Bobcat', image_name: 'Bobcat', real: 'Real')
    Animal.create(search_name: 'Bolognese Dog', image_name: 'Bolognese-Dog', real: 'Real')
    Animal.create(search_name: 'Bombay', image_name: 'Bombay', real: 'Real')
    Animal.create(search_name: 'Bongo', image_name: 'Bongo', real: 'Real')
    Animal.create(search_name: 'Bonito Fish', image_name: 'Bonito-Fish', real: 'Real')
    Animal.create(search_name: 'Bonobo', image_name: 'Bonobo', real: 'Real')
    Animal.create(search_name: 'Booby', image_name: 'Booby', real: 'Real')
    Animal.create(search_name: 'Border Collie', image_name: 'Border-Collie', real: 'Real')
    Animal.create(search_name: 'Border Terrier', image_name: 'Border-Terrier', real: 'Real')
    Animal.create(search_name: 'Bornean Orangutan', image_name: 'Bornean-Orangutan', real: 'Real')
    Animal.create(search_name: 'Borneo Elephant', image_name: 'Borneo-Elephant', real: 'Real')
    Animal.create(search_name: 'Boston Terrier', image_name: 'Boston-Terrier', real: 'Real')
    Animal.create(search_name: 'Bottlenose Dolphin', image_name: 'Bottlenose-Dolphin', real: 'Real')
    Animal.create(search_name: 'Bowhead Whale', image_name: 'Bowhead-Whale', real: 'Real')
    Animal.create(search_name: 'Boxer Dog', image_name: 'Boxer-Dog', real: 'Real')
    Animal.create(search_name: 'Boykin Spaniel', image_name: 'Boykin-Spaniel', real: 'Real')
    Animal.create(search_name: 'Brazilian Terrier', image_name: 'Brazilian-Terrier', real: 'Real')
    Animal.create(search_name: 'British Timber', image_name: 'British-Timber', real: 'Real')
    Animal.create(search_name: 'Brown Bear', image_name: 'Brown-Bear', real: 'Real')
    Animal.create(search_name: 'Budgerigar', image_name: 'Budgerigar', real: 'Real')
    Animal.create(search_name: 'Buffalo', image_name: 'Buffalo', real: 'Real')
    Animal.create(search_name: 'Bull Shark', image_name: 'Bull-Shark', real: 'Real')
    Animal.create(search_name: 'Bull Terrier', image_name: 'Bull-Terrier', real: 'Real')
    Animal.create(search_name: 'Bulldog', image_name: 'Bulldog', real: 'Real')
    Animal.create(search_name: 'Bullfrog', image_name: 'Bullfrog', real: 'Real')
    Animal.create(search_name: 'Bullmastiff', image_name: 'Bullmastiff', real: 'Real')
    Animal.create(search_name: 'Bumblebee', image_name: 'Bumblebee', real: 'Real')
    Animal.create(search_name: 'Burmese', image_name: 'Burmese', real: 'Real')
    Animal.create(search_name: 'Burrowing Frog', image_name: 'Burrowing-Frog', real: 'Real')
    Animal.create(search_name: 'Butterfly', image_name: 'Butterfly', real: 'Real')
    Animal.create(search_name: 'Butterfly Fish', image_name: 'Butterfly-Fish', real: 'Real')
    Animal.create(search_name: 'Caiman', image_name: 'Caiman', real: 'Real')
    Animal.create(search_name: 'Cairn Terrier', image_name: 'Cairn-Terrier', real: 'Real')
    Animal.create(search_name: 'Camel', image_name: 'Camel', real: 'Real')
    Animal.create(search_name: 'Camel Spider', image_name: 'Camel-Spider', real: 'Real')
    Animal.create(search_name: 'Canaan Dog', image_name: 'Canaan-Dog', real: 'Real')
    Animal.create(search_name: 'Canadian Eskimo Dog', image_name: 'Canadian-Eskimo-Dog', real: 'Real')
    Animal.create(search_name: 'Capybara', image_name: 'Capybara', real: 'Real')
    Animal.create(search_name: 'Caracal', image_name: 'Caracal', real: 'Real')
    Animal.create(search_name: 'Carolina Dog', image_name: 'Carolina-Dog', real: 'Real')
    Animal.create(search_name: 'Cassowary', image_name: 'Cassowary', real: 'Real')
    Animal.create(search_name: 'Cat', image_name: 'Cat', real: 'Real')
    Animal.create(search_name: 'Caterpillar', image_name: 'Caterpillar', real: 'Real')
    Animal.create(search_name: 'Catfish', image_name: 'Catfish', real: 'Real')
    Animal.create(search_name: 'Cavalier King Charles Spaniel', image_name: 'Cavalier-King-Charles-Spaniel', real: 'Real')
    Animal.create(search_name: 'Centipede', image_name: 'Centipede', real: 'Real')
    Animal.create(search_name: 'Cesky Fousek', image_name: 'Cesky-Fousek', real: 'Real')
    Animal.create(search_name: 'Chameleon', image_name: 'Chameleon', real: 'Real')
    Animal.create(search_name: 'Chamois', image_name: 'Chamois', real: 'Real')
    Animal.create(search_name: 'Cheetah', image_name: 'Cheetah', real: 'Real')
    Animal.create(search_name: 'Chesapeake Bay Retriever', image_name: 'Chesapeake-Bay-Retriever', real: 'Real')
    Animal.create(search_name: 'Chicken', image_name: 'Chicken', real: 'Real')
    Animal.create(search_name: 'Chihuahua', image_name: 'Chihuahua', real: 'Real')
    Animal.create(search_name: 'Chimaera', image_name: 'Chimaera', real: 'Real')
    Animal.create(search_name: 'Chimpanzee', image_name: 'Chimpanzee', real: 'Real')
    Animal.create(search_name: 'Chinchilla', image_name: 'Chinchilla', real: 'Real')
    Animal.create(search_name: 'Chinese Crested Dog', image_name: 'Chinese-Crested-Dog', real: 'Real')
    Animal.create(search_name: 'Chinook', image_name: 'Chinook', real: 'Real')
    Animal.create(search_name: 'Chinstrap Penguin', image_name: 'Chinstrap-Penguin', real: 'Real')
    Animal.create(search_name: 'Chipmunk', image_name: 'Chipmunk', real: 'Real')
    Animal.create(search_name: 'Chow Chow', image_name: 'Chow-Chow', real: 'Real')
    Animal.create(search_name: 'Cichlid', image_name: 'Cichlid', real: 'Real')
    Animal.create(search_name: 'Clouded Leopard', image_name: 'Clouded-Leopard', real: 'Real')
    Animal.create(search_name: 'Clownfish', image_name: 'Clownfish', real: 'Real')
    Animal.create(search_name: 'Clumber Spaniel', image_name: 'Clumber-Spaniel', real: 'Real')
    Animal.create(search_name: 'Coati', image_name: 'Coati', real: 'Real')
    Animal.create(search_name: 'Cockatoo', image_name: 'Cockatoo', real: 'Real')
    Animal.create(search_name: 'Cockroach', image_name: 'Cockroach', real: 'Real')
    Animal.create(search_name: 'Collared Peccary', image_name: 'Collared-Peccary', real: 'Real')
    Animal.create(search_name: 'Collie', image_name: 'Collie', real: 'Real')
    Animal.create(search_name: 'Colossal Squid', image_name: 'Colossal-Squid', real: 'Real')
    Animal.create(search_name: 'Common Buzzard', image_name: 'Common-Buzzard', real: 'Real')
    Animal.create(search_name: 'Common Frog', image_name: 'Common-Frog', real: 'Real')
    Animal.create(search_name: 'Common Loon', image_name: 'Common-Loon', real: 'Real')
    Animal.create(search_name: 'Common Toad', image_name: 'Common-Toad', real: 'Real')
    Animal.create(search_name: 'Cooper’s Hawk', image_name: 'Cooper’s-Hawk', real: 'Real')
    Animal.create(search_name: 'Coral', image_name: 'Coral', real: 'Real')
    Animal.create(search_name: 'Cotton-top Tamarin', image_name: 'Cotton-top-Tamarin', real: 'Real')
    Animal.create(search_name: 'Cougar', image_name: 'Cougar', real: 'Real')
    Animal.create(search_name: 'Cow', image_name: 'Cow', real: 'Real')
    Animal.create(search_name: 'Coyote', image_name: 'Coyote', real: 'Real')
    Animal.create(search_name: 'Crab', image_name: 'Crab', real: 'Real')
    Animal.create(search_name: 'Crab-eating Macaque', image_name: 'Crab-eating-Macaque', real: 'Real')
    Animal.create(search_name: 'Crane', image_name: 'Crane', real: 'Real')
    Animal.create(search_name: 'Crested Penguin', image_name: 'Crested-Penguin', real: 'Real')
    Animal.create(search_name: 'Crocodile', image_name: 'Crocodile', real: 'Real')
    Animal.create(search_name: 'Cross River Gorilla', image_name: 'Cross-River-Gorilla', real: 'Real')
    Animal.create(search_name: 'Curly Coated Retriever', image_name: 'Curly-Coated-Retriever', real: 'Real')
    Animal.create(search_name: 'Cuscus', image_name: 'Cuscus', real: 'Real')
    Animal.create(search_name: 'Cuttlefish', image_name: 'Cuttlefish', real: 'Real')
    Animal.create(search_name: 'Dabra Goby', image_name: 'Dabra-Goby', real: 'Real')
    Animal.create(search_name: 'Dachshund', image_name: 'Dachshund', real: 'Real')
    Animal.create(search_name: 'Dalmatian', image_name: 'Dalmatian', real: 'Real')
    Animal.create(search_name: 'Damselfish', image_name: 'Damselfish', real: 'Real')
    Animal.create(search_name: 'Dark-eyed Junco', image_name: 'Dark-eyed-Junco', real: 'Real')
    Animal.create(search_name: 'Darwin’s Frog', image_name: 'Darwin’s-Frog', real: 'Real')
    Animal.create(search_name: 'Dassie Rat', image_name: 'Dassie-Rat', real: 'Real')
    Animal.create(search_name: 'Deer', image_name: 'Deer', real: 'Real')
    Animal.create(search_name: 'Degu', image_name: 'Degu', real: 'Real')
    Animal.create(search_name: 'Desert Tortoise', image_name: 'Desert-Tortoise', real: 'Real')
    Animal.create(search_name: 'Deutsche Bracke', image_name: 'Deutsche-Bracke', real: 'Real')
    Animal.create(search_name: 'Dhole', image_name: 'Dhole', real: 'Real')
    Animal.create(search_name: 'Dik-Dik', image_name: 'Dik-Dik', real: 'Real')
    Animal.create(search_name: 'Dingo', image_name: 'Dingo', real: 'Real')
    Animal.create(search_name: 'Dipper', image_name: 'Dipper', real: 'Real')
    Animal.create(search_name: 'Discus', image_name: 'Discus', real: 'Real')
    Animal.create(search_name: 'Doberman Pinscher', image_name: 'Doberman-Pinscher', real: 'Real')
    Animal.create(search_name: 'Dodo', image_name: 'Dodo', real: 'Real')
    Animal.create(search_name: 'Dog', image_name: 'Dog', real: 'Real')
    Animal.create(search_name: 'Dogo Argentino', image_name: 'Dogo-Argentino', real: 'Real')
    Animal.create(search_name: 'Dogue De Bordeaux', image_name: 'Dogue-De-Bordeaux', real: 'Real')
    Animal.create(search_name: 'Dolphin', image_name: 'Dolphin', real: 'Real')
    Animal.create(search_name: 'Donkey', image_name: 'Donkey', real: 'Real')
    Animal.create(search_name: 'Dormouse', image_name: 'Dormouse', real: 'Real')
    Animal.create(search_name: 'Dotterel', image_name: 'Dotterel', real: 'Real')
    Animal.create(search_name: 'Dove', image_name: 'Dove', real: 'Real')
    Animal.create(search_name: 'Dragonfish', image_name: 'Dragonfish', real: 'Real')
    Animal.create(search_name: 'Drever', image_name: 'Drever', real: 'Real')
    Animal.create(search_name: 'Dromedary Camel', image_name: 'Dromedary-Camel', real: 'Real')
    Animal.create(search_name: 'Drongo', image_name: 'Drongo', real: 'Real')
    Animal.create(search_name: 'Drum Fish', image_name: 'Drum-Fish', real: 'Real')
    Animal.create(search_name: 'Duck', image_name: 'Duck', real: 'Real')
    Animal.create(search_name: 'Dugong', image_name: 'Dugong', real: 'Real')
    Animal.create(search_name: 'Dunker', image_name: 'Dunker', real: 'Real')
    Animal.create(search_name: 'Dung Beetle', image_name: 'Dung-Beetle', real: 'Real')
    Animal.create(search_name: 'Dunlin', image_name: 'Dunlin', real: 'Real')
    Animal.create(search_name: 'Dusky Dolphin', image_name: 'Dusky-Dolphin', real: 'Real')
    Animal.create(search_name: 'Dwarf Crocodile', image_name: 'Dwarf-Crocodile', real: 'Real')
    Animal.create(search_name: 'Eagle', image_name: 'Eagle', real: 'Real')
    Animal.create(search_name: 'Eartheater', image_name: 'Eartheater', real: 'Real')
    Animal.create(search_name: 'Earthworm', image_name: 'Earthworm', real: 'Real')
    Animal.create(search_name: 'Earwig', image_name: 'Earwig', real: 'Real')
    Animal.create(search_name: 'Eastern Gorilla', image_name: 'Eastern-Gorilla', real: 'Real')
    Animal.create(search_name: 'Eastern Lowland Gorilla', image_name: 'Eastern-Lowland-Gorilla', real: 'Real')
    Animal.create(search_name: 'Echidna', image_name: 'Echidna', real: 'Real')
    Animal.create(search_name: 'Edible Frog', image_name: 'Edible-Frog', real: 'Real')
    Animal.create(search_name: 'Egyptian Mau', image_name: 'Egyptian-Mau', real: 'Real')
    Animal.create(search_name: 'Eelpout', image_name: 'Eelpout', real: 'Real')
    Animal.create(search_name: 'Electric Eel', image_name: 'Electric-Eel', real: 'Real')
    Animal.create(search_name: 'Eft', image_name: 'Eft', real: 'Real')
    Animal.create(search_name: 'Egret', image_name: 'Egret', real: 'Real')
    Animal.create(search_name: 'Eider', image_name: 'Eider', real: 'Real')
    Animal.create(search_name: 'Eland', image_name: 'Eland', real: 'Real')
    Animal.create(search_name: 'Elepaio', image_name: 'Elepaio', real: 'Real')
    Animal.create(search_name: 'Elephant', image_name: 'Elephant', real: 'Real')
    Animal.create(search_name: 'Elephant Seal', image_name: 'Elephant-Seal', real: 'Real')
    Animal.create(search_name: 'Elephant Shrew', image_name: 'Elephant-Shrew', real: 'Real')
    Animal.create(search_name: 'Elk', image_name: 'Elk', real: 'Real')
    Animal.create(search_name: 'Emperor Penguin', image_name: 'Emperor-Penguin', real: 'Real')
    Animal.create(search_name: 'Emperor Tamarin', image_name: 'Emperor-Tamarin', real: 'Real')
    Animal.create(search_name: 'Emu', image_name: 'Emu', real: 'Real')
    Animal.create(search_name: 'English Cocker Spaniel', image_name: 'English-Cocker-Spaniel', real: 'Real')
    Animal.create(search_name: 'English Shepherd', image_name: 'English-Shepherd', real: 'Real')
    Animal.create(search_name: 'English Springer Spaniel', image_name: 'English-Springer-Spaniel', real: 'Real')
    Animal.create(search_name: 'Entlebucher Mountain Dog', image_name: 'Entlebucher-Mountain-Dog', real: 'Real')
    Animal.create(search_name: 'Epagneul Pont Audemer', image_name: 'Epagneul-Pont-Audemer', real: 'Real')
    Animal.create(search_name: 'Ermine', image_name: 'Ermine', real: 'Real')
    Animal.create(search_name: 'Escolar', image_name: 'Escolar', real: 'Real')
    Animal.create(search_name: 'Eskimo Dog', image_name: 'Eskimo-Dog', real: 'Real')
    Animal.create(search_name: 'Estrela Mountain Dog', image_name: 'Estrela-Mountain-Dog', real: 'Real')
    Animal.create(search_name: 'Eulachon', image_name: 'Eulachon', real: 'Real')
    Animal.create(search_name: 'Euro', image_name: 'Euro', real: 'Real')
    Animal.create(search_name: 'Falcon', image_name: 'Falcon', real: 'Real')
    Animal.create(search_name: 'False Killer Whale', image_name: 'False-Killer-Whale', real: 'Real')
    Animal.create(search_name: 'Fangtooth', image_name: 'Fangtooth', real: 'Real')
    Animal.create(search_name: 'Fennec Fox', image_name: 'Fennec-Fox', real: 'Real')
    Animal.create(search_name: 'Ferret', image_name: 'Ferret', real: 'Real')
    Animal.create(search_name: 'Field Spaniel', image_name: 'Field-Spaniel', real: 'Real')
    Animal.create(search_name: 'Fiddler Crab', image_name: 'Fiddler-Crab', real: 'Real')
    Animal.create(search_name: 'Finch', image_name: 'Finch', real: 'Real')
    Animal.create(search_name: 'Fin Whale', image_name: 'Fin-Whale', real: 'Real')
    Animal.create(search_name: 'Finnish Spitz', image_name: 'Finnish-Spitz', real: 'Real')
    Animal.create(search_name: 'Fire Ant', image_name: 'Fire-Ant', real: 'Real')
    Animal.create(search_name: 'Fire-bellied Toad', image_name: 'Fire-bellied-Toad', real: 'Real')
    Animal.create(search_name: 'Fish', image_name: 'Fish', real: 'Real')
    Animal.create(search_name: 'Fishing Cat', image_name: 'Fishing-Cat', real: 'Real')
    Animal.create(search_name: 'Flamingo', image_name: 'Flamingo', real: 'Real')
    Animal.create(search_name: 'Flat-coated Retriever', image_name: 'Flat-coated-Retriever', real: 'Real')
    Animal.create(search_name: 'Flat-headed Cat', image_name: 'Flat-headed-Cat', real: 'Real')
    Animal.create(search_name: 'Flat-headed Snake', image_name: 'Flat-headed-Snake', real: 'Real')
    Animal.create(search_name: 'Flea', image_name: 'Flea', real: 'Real')
    Animal.create(search_name: 'Flounder', image_name: 'Flounder', real: 'Real')
    Animal.create(search_name: 'Flowerpecker', image_name: 'Flowerpecker', real: 'Real')
    Animal.create(search_name: 'Fluke Fish', image_name: 'Fluke-Fish', real: 'Real')
    Animal.create(search_name: 'Fly', image_name: 'Fly', real: 'Real')
    Animal.create(search_name: 'Flying Squirrel', image_name: 'Flying-Squirrel', real: 'Real')
    Animal.create(search_name: 'Fossa', image_name: 'Fossa', real: 'Real')
    Animal.create(search_name: 'Fox', image_name: 'Fox', real: 'Real')
    Animal.create(search_name: 'Fox Terrier', image_name: 'Fox-Terrier', real: 'Real')
    Animal.create(search_name: 'French Bulldog', image_name: 'French-Bulldog', real: 'Real')
    Animal.create(search_name: 'Frigatebird', image_name: 'Frigatebird', real: 'Real')
    Animal.create(search_name: 'Frilled Lizard', image_name: 'Frilled-Lizard', real: 'Real')
    Animal.create(search_name: 'Frilled Shark', image_name: 'Frilled-Shark', real: 'Real')
    Animal.create(search_name: 'Frog', image_name: 'Frog', real: 'Real')
    Animal.create(search_name: 'Frogmouth', image_name: 'Frogmouth', real: 'Real')
    Animal.create(search_name: 'Fulmar', image_name: 'Fulmar', real: 'Real')
    Animal.create(search_name: 'Fur Seal', image_name: 'Fur-Seal', real: 'Real')
    Animal.create(search_name: 'Galapagos Penguin', image_name: 'Galapagos-Penguin', real: 'Real')
    Animal.create(search_name: 'Galapagos Tortoise', image_name: 'Galapagos-Tortoise', real: 'Real')
    Animal.create(search_name: 'Gar', image_name: 'Gar', real: 'Real')
    Animal.create(search_name: 'Gecko', image_name: 'Gecko', real: 'Real')
    Animal.create(search_name: 'Gentoo Penguin', image_name: 'Gentoo-Penguin', real: 'Real')
    Animal.create(search_name: 'Geoffroy’s Tamarin', image_name: 'Geoffroy’s-Tamarin', real: 'Real')
    Animal.create(search_name: 'Gerbil', image_name: 'Gerbil', real: 'Real')
    Animal.create(search_name: 'German Pinscher', image_name: 'German-Pinscher', real: 'Real')
    Animal.create(search_name: 'German Shepherd', image_name: 'German-Shepherd', real: 'Real')
    Animal.create(search_name: 'Gharial', image_name: 'Gharial', real: 'Real')
    Animal.create(search_name: 'Giant African Land Snail', image_name: 'Giant-African-Land-Snail', real: 'Real')
    Animal.create(search_name: 'Giant Clam', image_name: 'Giant-Clam', real: 'Real')
    Animal.create(search_name: 'Giant Panda Bear', image_name: 'Giant-Panda-Bear', real: 'Real')
    Animal.create(search_name: 'Giant Schnauzer', image_name: 'Giant-Schnauzer', real: 'Real')
    Animal.create(search_name: 'Gibbon', image_name: 'Gibbon', real: 'Real')
    Animal.create(search_name: 'Gila Monster', image_name: 'Gila-Monster', real: 'Real')
    Animal.create(search_name: 'Giraffe', image_name: 'Giraffe', real: 'Real')
    Animal.create(search_name: 'Glass Lizard', image_name: 'Glass-Lizard', real: 'Real')
    Animal.create(search_name: 'Glow Worm', image_name: 'Glow-Worm', real: 'Real')
    Animal.create(search_name: 'Goat', image_name: 'Goat', real: 'Real')
    Animal.create(search_name: 'Goblin Shark', image_name: 'Goblin-Shark', real: 'Real')
    Animal.create(search_name: 'Golden Lion Tamarin', image_name: 'Golden-Lion-Tamarin', real: 'Real')
    Animal.create(search_name: 'Golden Masked Owl', image_name: 'Golden-Masked-Owl', real: 'Real')
    Animal.create(search_name: 'Golden Oriole', image_name: 'Golden-Oriole', real: 'Real')
    Animal.create(search_name: 'Golden Retriever', image_name: 'Golden-Retriever', real: 'Real')
    Animal.create(search_name: 'Golden-Crowned Flying Fox', image_name: 'Golden-Crowned-Flying-Fox', real: 'Real')
    Animal.create(search_name: 'Goose', image_name: 'Goose', real: 'Real')
    Animal.create(search_name: 'Gopher', image_name: 'Gopher', real: 'Real')
    Animal.create(search_name: 'Gorilla', image_name: 'Gorilla', real: 'Real')
    Animal.create(search_name: 'Grasshopper', image_name: 'Grasshopper', real: 'Real')
    Animal.create(search_name: 'Great Dane', image_name: 'Great-Dane', real: 'Real')
    Animal.create(search_name: 'Great Pyrenees', image_name: 'Great-Pyrenees', real: 'Real')
    Animal.create(search_name: 'Great White Shark', image_name: 'Great-White-Shark', real: 'Real')
    Animal.create(search_name: 'Greater Swiss Mountain Dog', image_name: 'Greater-Swiss-Mountain-Dog', real: 'Real')
    Animal.create(search_name: 'Green Anole', image_name: 'Green-Anole', real: 'Real')
    Animal.create(search_name: 'Green Bee-Eater', image_name: 'Green-Bee-Eater', real: 'Real')
    Animal.create(search_name: 'Greenland Dog', image_name: 'Greenland-Dog', real: 'Real')
    Animal.create(search_name: 'Grey Mouse Lemur', image_name: 'Grey-Mouse-Lemur', real: 'Real')
    Animal.create(search_name: 'Grey Reef Shark', image_name: 'Grey-Reef-Shark', real: 'Real')
    Animal.create(search_name: 'Grey Seal', image_name: 'Grey-Seal', real: 'Real')
    Animal.create(search_name: 'Greyhound', image_name: 'Greyhound', real: 'Real')
    Animal.create(search_name: 'Grizzly Bear', image_name: 'Grizzly-Bear', real: 'Real')
    Animal.create(search_name: 'Grouse', image_name: 'Grouse', real: 'Real')
    Animal.create(search_name: 'Guinea Fowl', image_name: 'Guinea-Fowl', real: 'Real')
    Animal.create(search_name: 'Guinea Pig', image_name: 'Guinea-Pig', real: 'Real')
    Animal.create(search_name: 'Guppy', image_name: 'Guppy', real: 'Real')
    Animal.create(search_name: 'Haddock', image_name: 'Haddock', real: 'Real')
    Animal.create(search_name: 'Hagfish', image_name: 'Hagfish', real: 'Real')
    Animal.create(search_name: 'Hake', image_name: 'Hake', real: 'Real')
    Animal.create(search_name: 'Halibut', image_name: 'Halibut', real: 'Real')
    Animal.create(search_name: 'Hamerkop Bird', image_name: 'Hamerkop-Bird', real: 'Real')
    Animal.create(search_name: 'Hammerhead Shark', image_name: 'Hammerhead-Shark', real: 'Real')
    Animal.create(search_name: 'Hamster', image_name: 'Hamster', real: 'Real')
    Animal.create(search_name: 'Harbor Porpoise', image_name: 'Harbor-Porpoise', real: 'Real')
    Animal.create(search_name: 'Harbor Seal', image_name: 'Harbor-Seal', real: 'Real')
    Animal.create(search_name: 'Hare', image_name: 'Hare', real: 'Real')
    Animal.create(search_name: 'Harp Seal', image_name: 'Harp-Seal', real: 'Real')
    Animal.create(search_name: 'Harpy Eagle', image_name: 'Harpy-Eagle', real: 'Real')
    Animal.create(search_name: 'Harrier Hawk', image_name: 'Harrier-Hawk', real: 'Real')
    Animal.create(search_name: 'Hartebeest', image_name: 'Hartebeest', real: 'Real')
    Animal.create(search_name: 'Havanese', image_name: 'Havanese', real: 'Real')
    Animal.create(search_name: 'Hawaiian Crow', image_name: 'Hawaiian-Crow', real: 'Real')
    Animal.create(search_name: 'Hawk', image_name: 'Hawk', real: 'Real')
    Animal.create(search_name: 'Hazel Dormouse', image_name: 'Hazel-Dormouse', real: 'Real')
    Animal.create(search_name: 'Hedgehog', image_name: 'Hedgehog', real: 'Real')
    Animal.create(search_name: 'Hellbender', image_name: 'Hellbender', real: 'Real')
    Animal.create(search_name: 'Hercules Beetle', image_name: 'Hercules-Beetle', real: 'Real')
    Animal.create(search_name: 'Hermit Crab', image_name: 'Hermit-Crab', real: 'Real')
    Animal.create(search_name: 'Heron', image_name: 'Heron', real: 'Real')
    Animal.create(search_name: 'Herring', image_name: 'Herring', real: 'Real')
    Animal.create(search_name: 'Highland Cattle', image_name: 'Highland-Cattle', real: 'Real')
    Animal.create(search_name: 'Hippopotamus', image_name: 'Hippopotamus', real: 'Real')
    Animal.create(search_name: 'Hissing Cockroach', image_name: 'Hissing-Cockroach', real: 'Real')
    Animal.create(search_name: 'Hoatzin', image_name: 'Hoatzin', real: 'Real')
    Animal.create(search_name: 'Honey Badger', image_name: 'Honey-Badger', real: 'Real')
    Animal.create(search_name: 'Honey Bee', image_name: 'Honey-Bee', real: 'Real')
    Animal.create(search_name: 'Hoopoe', image_name: 'Hoopoe', real: 'Real')
    Animal.create(search_name: 'Horn Shark', image_name: 'Horn-Shark', real: 'Real')
    Animal.create(search_name: 'Hornbill', image_name: 'Hornbill', real: 'Real')
    Animal.create(search_name: 'Horned Frog', image_name: 'Horned-Frog', real: 'Real')
    Animal.create(search_name: 'Horned Puffin', image_name: 'Horned-Puffin', real: 'Real')
    Animal.create(search_name: 'Hornet', image_name: 'Hornet', real: 'Real')
    Animal.create(search_name: 'Horse', image_name: 'Horse', real: 'Real')
    Animal.create(search_name: 'Horseshoe Crab', image_name: 'Horseshoe-Crab', real: 'Real')
    Animal.create(search_name: 'House Finch', image_name: 'House-Finch', real: 'Real')
    Animal.create(search_name: 'House Martin', image_name: 'House-Martin', real: 'Real')
    Animal.create(search_name: 'House Mouse', image_name: 'House-Mouse', real: 'Real')
    Animal.create(search_name: 'House Sparrow', image_name: 'House-Sparrow', real: 'Real')
    Animal.create(search_name: 'House Wren', image_name: 'House-Wren', real: 'Real')
    Animal.create(search_name: 'Hoverfly', image_name: 'Hoverfly', real: 'Real')
    Animal.create(search_name: 'Howler Monkey', image_name: 'Howler-Monkey', real: 'Real')
    Animal.create(search_name: 'Humboldt Penguin', image_name: 'Humboldt-Penguin', real: 'Real')
    Animal.create(search_name: 'Hummingbird', image_name: 'Hummingbird', real: 'Real')
    Animal.create(search_name: 'Humpback Whale', image_name: 'Humpback-Whale', real: 'Real')
    Animal.create(search_name: 'Humphead Wrasse', image_name: 'Humphead-Wrasse', real: 'Real')
    Animal.create(search_name: 'Huntsman Spider', image_name: 'Huntsman-Spider', real: 'Real')
    Animal.create(search_name: 'Hyena', image_name: 'Hyena', real: 'Real')
    Animal.create(search_name: 'Hyrax', image_name: 'Hyrax', real: 'Real')
    Animal.create(search_name: 'Iberian Frog', image_name: 'Iberian-Frog', real: 'Real')
    Animal.create(search_name: 'Ibex', image_name: 'Ibex', real: 'Real')
    Animal.create(search_name: 'Ibis', image_name: 'Ibis', real: 'Real')
    Animal.create(search_name: 'Ibizan Hound', image_name: 'Ibizan-Hound', real: 'Real')
    Animal.create(search_name: 'Icefish', image_name: 'Icefish', real: 'Real')
    Animal.create(search_name: 'Iceland Gull', image_name: 'Iceland-Gull', real: 'Real')
    Animal.create(search_name: 'Icterine Warbler', image_name: 'Icterine-Warbler', real: 'Real')
    Animal.create(search_name: 'Idaho Ground Squirrel', image_name: 'Idaho-Ground-Squirrel', real: 'Real')
    Animal.create(search_name: 'Idaho Pocket Gopher', image_name: 'Idaho-Pocket-Gopher', real: 'Real')
    Animal.create(search_name: 'Iguana', image_name: 'Iguana', real: 'Real')
    Animal.create(search_name: 'Immortal Jellyfish', image_name: 'Immortal-Jellyfish', real: 'Real')
    Animal.create(search_name: 'Impala', image_name: 'Impala', real: 'Real')
    Animal.create(search_name: 'Imperial Eagle', image_name: 'Imperial-Eagle', real: 'Real')
    Animal.create(search_name: 'Inchworm', image_name: 'Inchworm', real: 'Real')
    Animal.create(search_name: 'Indian Bullfrog', image_name: 'Indian-Bullfrog', real: 'Real')
    Animal.create(search_name: 'Indian Bush Rat', image_name: 'Indian-Bush-Rat', real: 'Real')
    Animal.create(search_name: 'Indian Elephant', image_name: 'Indian-Elephant', real: 'Real')
    Animal.create(search_name: 'Indian Flying Fox', image_name: 'Indian-Flying-Fox', real: 'Real')
    Animal.create(search_name: 'Indian Gazelle', image_name: 'Indian-Gazelle', real: 'Real')
    Animal.create(search_name: 'Indian Gerbil', image_name: 'Indian-Gerbil', real: 'Real')
    Animal.create(search_name: 'Indian Hare', image_name: 'Indian-Hare', real: 'Real')
    Animal.create(search_name: 'Indian Palm Squirrel', image_name: 'Indian-Palm-Squirrel', real: 'Real')
    Animal.create(search_name: 'Indian Rhinoceros', image_name: 'Indian-Rhinoceros', real: 'Real')
    Animal.create(search_name: 'Indian Star Tortoise', image_name: 'Indian-Star-Tortoise', real: 'Real')
    Animal.create(search_name: 'Indochinese Tiger', image_name: 'Indochinese-Tiger', real: 'Real')
    Animal.create(search_name: 'Indri', image_name: 'Indri', real: 'Real')
    Animal.create(search_name: 'Inland Taipan', image_name: 'Inland-Taipan', real: 'Real')
    Animal.create(search_name: 'Insect', image_name: 'Insect', real: 'Real')
    Animal.create(search_name: 'Insular Mole', image_name: 'Insular-Mole', real: 'Real')
    Animal.create(search_name: 'Inyo Shrew', image_name: 'Inyo-Shrew', real: 'Real')
    Animal.create(search_name: 'Iriomote Cat', image_name: 'Iriomote-Cat', real: 'Real')
    Animal.create(search_name: 'Irish Setter', image_name: 'Irish-Setter', real: 'Real')
    Animal.create(search_name: 'Irish Wolfhound', image_name: 'Irish-Wolfhound', real: 'Real')
    Animal.create(search_name: 'Irukandji Jellyfish', image_name: 'Irukandji-Jellyfish', real: 'Real')
    Animal.create(search_name: 'Island Gray Fox', image_name: 'Island-Gray-Fox', real: 'Real')
    Animal.create(search_name: 'Island Mouse', image_name: 'Island-Mouse', real: 'Real')
    Animal.create(search_name: 'Isopod', image_name: 'Isopod', real: 'Real')
    Animal.create(search_name: 'Italian Greyhound', image_name: 'Italian-Greyhound', real: 'Real')
    Animal.create(search_name: 'Italian Wall Lizard', image_name: 'Italian-Wall-Lizard', real: 'Real')
    Animal.create(search_name: 'Italian Wolf', image_name: 'Italian-Wolf', real: 'Real')
    Animal.create(search_name: 'Ivory Gull', image_name: 'Ivory-Gull', real: 'Real')
    Animal.create(search_name: 'Jabiru', image_name: 'Jabiru', real: 'Real')
    Animal.create(search_name: 'Jacamar', image_name: 'Jacamar', real: 'Real')
    Animal.create(search_name: 'Jacana', image_name: 'Jacana', real: 'Real')
    Animal.create(search_name: 'Jackal', image_name: 'Jackal', real: 'Real')
    Animal.create(search_name: 'Jack Rabbit', image_name: 'Jack-Rabbit', real: 'Real')
    Animal.create(search_name: 'Jack Russel', image_name: 'Jack-Russel', real: 'Real')
    Animal.create(search_name: 'Jaeger', image_name: 'Jaeger', real: 'Real')
    Animal.create(search_name: 'Jaguar', image_name: 'Jaguar', real: 'Real')
    Animal.create(search_name: 'Jaguarundi', image_name: 'Jaguarundi', real: 'Real')
    Animal.create(search_name: 'Japanese Chin', image_name: 'Japanese-Chin', real: 'Real')
    Animal.create(search_name: 'Japanese Hare', image_name: 'Japanese-Hare', real: 'Real')
    Animal.create(search_name: 'Japanese Macaque', image_name: 'Japanese-Macaque', real: 'Real')
    Animal.create(search_name: 'Japanese Mole', image_name: 'Japanese-Mole', real: 'Real')
    Animal.create(search_name: 'Japanese Squirrel', image_name: 'Japanese-Squirrel', real: 'Real')
    Animal.create(search_name: 'Javan Langur', image_name: 'Javan-Langur', real: 'Real')
    Animal.create(search_name: 'Javan Pig', image_name: 'Javan-Pig', real: 'Real')
    Animal.create(search_name: 'Javan Pipistrelle', image_name: 'Javan-Pipistrelle', real: 'Real')
    Animal.create(search_name: 'Javan Rhinoceros', image_name: 'Javan-Rhinoceros', real: 'Real')
    Animal.create(search_name: 'Javan Slit-faced Bat', image_name: 'Javan-Slit-faced-Bat', real: 'Real')
    Animal.create(search_name: 'Javan Tree Shrew', image_name: 'Javan-Tree-Shrew', real: 'Real')
    Animal.create(search_name: 'Javanese', image_name: 'Javanese', real: 'Real')
    Animal.create(search_name: 'Jay', image_name: 'Jay', real: 'Real')
    Animal.create(search_name: 'Jellyfish', image_name: 'Jellyfish', real: 'Real')
    Animal.create(search_name: 'Jerboa', image_name: 'Jerboa', real: 'Real')
    Animal.create(search_name: 'Jico Deer Mouse', image_name: 'Jico-Deer-Mouse', real: 'Real')
    Animal.create(search_name: 'John Dory', image_name: 'John-Dory', real: 'Real')
    Animal.create(search_name: 'Jumping Spider', image_name: 'Jumping-Spider', real: 'Real')
    Animal.create(search_name: 'Junco', image_name: 'Junco', real: 'Real')
    Animal.create(search_name: 'Jungle Cat', image_name: 'Jungle-Cat', real: 'Real')
    Animal.create(search_name: 'Junglefowl', image_name: 'Junglefowl', real: 'Real')
    Animal.create(search_name: 'Jungle Palm Squirrel', image_name: 'Jungle-Palm-Squirrel', real: 'Real')
    Animal.create(search_name: 'Jungle Shrew', image_name: 'Jungle-Shrew', real: 'Real')
    Animal.create(search_name: 'Junin Grass Mouse', image_name: 'Junin-Grass-Mouse', real: 'Real')
    Animal.create(search_name: 'Junin Red Squirrel', image_name: 'Junin-Red-Squirrel', real: 'Real')
    Animal.create(search_name: 'Juniper Vole', image_name: 'Juniper-Vole', real: 'Real')
    Animal.create(search_name: 'Kagu', image_name: 'Kagu', real: 'Real')
    Animal.create(search_name: 'Kakapo', image_name: 'Kakapo', real: 'Real')
    Animal.create(search_name: 'Kangaroo', image_name: 'Kangaroo', real: 'Real')
    Animal.create(search_name: 'Kangaroo Rat', image_name: 'Kangaroo-Rat', real: 'Real')
    Animal.create(search_name: 'Katydid', image_name: 'Katydid', real: 'Real')
    Animal.create(search_name: 'Keel-Billed Toucan', image_name: 'Keel-Billed-Toucan', real: 'Real')
    Animal.create(search_name: 'Keeshond', image_name: 'Keeshond', real: 'Real')
    Animal.create(search_name: 'Kestrel', image_name: 'Kestrel', real: 'Real')
    Animal.create(search_name: 'Killer Whale', image_name: 'Killer-Whale', real: 'Real')
    Animal.create(search_name: 'King Cobra', image_name: 'King-Cobra', real: 'Real')
    Animal.create(search_name: 'King Crab', image_name: 'King-Crab', real: 'Real')
    Animal.create(search_name: 'King Penguin', image_name: 'King-Penguin', real: 'Real')
    Animal.create(search_name: 'Kingfisher', image_name: 'Kingfisher', real: 'Real')
    Animal.create(search_name: 'Kinkajou', image_name: 'Kinkajou', real: 'Real')
    Animal.create(search_name: 'Kirk’s Dik-Dik', image_name: 'Kirk’s-Dik-Dik', real: 'Real')
    Animal.create(search_name: 'Kite', image_name: 'Kite', real: 'Real')
    Animal.create(search_name: 'Kivu Shrew', image_name: 'Kivu-Shrew', real: 'Real')
    Animal.create(search_name: 'Kiwi', image_name: 'Kiwi', real: 'Real')
    Animal.create(search_name: 'Klipspringer', image_name: 'Klipspringer', real: 'Real')
    Animal.create(search_name: 'Knifefish', image_name: 'Knifefish', real: 'Real')
    Animal.create(search_name: 'Koala', image_name: 'Koala', real: 'Real')
    Animal.create(search_name: 'Kob', image_name: 'Kob', real: 'Real')
    Animal.create(search_name: 'Kodkod', image_name: 'Kodkod', real: 'Real')
    Animal.create(search_name: 'Komodo Dragon', image_name: 'Komodo-Dragon', real: 'Real')
    Animal.create(search_name: 'Kookaburra', image_name: 'Kookaburra', real: 'Real')
    Animal.create(search_name: 'Korean Field Mouse', image_name: 'Korean-Field-Mouse', real: 'Real')
    Animal.create(search_name: 'Korean Hare', image_name: 'Korean-Hare', real: 'Real')
    Animal.create(search_name: 'Korinch’s Rat', image_name: 'Korinch’s-Rat', real: 'Real')
    Animal.create(search_name: 'Kouprey', image_name: 'Kouprey', real: 'Real')
    Animal.create(search_name: 'Kowari', image_name: 'Kowari', real: 'Real')
    Animal.create(search_name: 'Krill', image_name: 'Krill', real: 'Real')
    Animal.create(search_name: 'Kudu', image_name: 'Kudu', real: 'Real')
    Animal.create(search_name: 'Kulan', image_name: 'Kulan', real: 'Real')
    Animal.create(search_name: 'Labradoodle', image_name: 'Labradoodle', real: 'Real')
    Animal.create(search_name: 'Labrador Retriever', image_name: 'Labrador-Retriever', real: 'Real')
    Animal.create(search_name: 'Lacewing', image_name: 'Lacewing', real: 'Real')
    Animal.create(search_name: 'Ladybug', image_name: 'Ladybug', real: 'Real')
    Animal.create(search_name: 'Lamb', image_name: 'Lamb', real: 'Real')
    Animal.create(search_name: 'Lammergeier', image_name: 'Lammergeier', real: 'Real')
    Animal.create(search_name: 'Lamprey', image_name: 'Lamprey', real: 'Real')
    Animal.create(search_name: 'Lapwing', image_name: 'Lapwing', real: 'Real')
    Animal.create(search_name: 'Leafcutter Ant', image_name: 'Leafcutter-Ant', real: 'Real')
    Animal.create(search_name: 'Leaf-Tailed Gecko', image_name: 'Leaf-Tailed-Gecko', real: 'Real')
    Animal.create(search_name: 'Leatherback Sea Turtle', image_name: 'Leatherback-Sea-Turtle', real: 'Real')
    Animal.create(search_name: 'Leech', image_name: 'Leech', real: 'Real')
    Animal.create(search_name: 'Lemming', image_name: 'Lemming', real: 'Real')
    Animal.create(search_name: 'Lemur', image_name: 'Lemur', real: 'Real')
    Animal.create(search_name: 'Leopard', image_name: 'Leopard', real: 'Real')
    Animal.create(search_name: 'Leopard Cat', image_name: 'Leopard-Cat', real: 'Real')
    Animal.create(search_name: 'Leopard Seal', image_name: 'Leopard-Seal', real: 'Real')
    Animal.create(search_name: 'Leopard Tortoise', image_name: 'Leopard-Tortoise', real: 'Real')
    Animal.create(search_name: 'Liger', image_name: 'Liger', real: 'Real')
    Animal.create(search_name: 'Lion', image_name: 'Lion', real: 'Real')
    Animal.create(search_name: 'Lionfish', image_name: 'Lionfish', real: 'Real')
    Animal.create(search_name: 'Little Penguin', image_name: 'Little-Penguin', real: 'Real')
    Animal.create(search_name: 'Lizard', image_name: 'Lizard', real: 'Real')
    Animal.create(search_name: 'Llama', image_name: 'Llama', real: 'Real')
    Animal.create(search_name: 'Loach', image_name: 'Loach', real: 'Real')
    Animal.create(search_name: 'Lobster', image_name: 'Lobster', real: 'Real')
    Animal.create(search_name: 'Long-Eared Owl', image_name: 'Long-Eared-Owl', real: 'Real')
    Animal.create(search_name: 'Long-Tailed Tit', image_name: 'Long-Tailed-Tit', real: 'Real')
    Animal.create(search_name: 'Longspur', image_name: 'Longspur', real: 'Real')
    Animal.create(search_name: 'Loon', image_name: 'Loon', real: 'Real')
    Animal.create(search_name: 'Loris', image_name: 'Loris', real: 'Real')
    Animal.create(search_name: 'Lory', image_name: 'Lory', real: 'Real')
    Animal.create(search_name: 'Lovebird', image_name: 'Lovebird', real: 'Real')
    Animal.create(search_name: 'Lungfish', image_name: 'Lungfish', real: 'Real')
    Animal.create(search_name: 'Lynx', image_name: 'Lynx', real: 'Real')
    Animal.create(search_name: 'Lyrebird', image_name: 'Lyrebird', real: 'Real')
    Animal.create(search_name: 'Macaroni Penguin', image_name: 'Macaroni-Penguin', real: 'Real')
    Animal.create(search_name: 'Macaw', image_name: 'Macaw', real: 'Real')
    Animal.create(search_name: 'Magellanic Penguin', image_name: 'Magellanic-Penguin', real: 'Real')
    Animal.create(search_name: 'Magpie', image_name: 'Magpie', real: 'Real')
    Animal.create(search_name: 'Maine Coon', image_name: 'Maine-Coon', real: 'Real')
    Animal.create(search_name: 'Malayan Civet', image_name: 'Malayan-Civet', real: 'Real')
    Animal.create(search_name: 'Malayan Tiger', image_name: 'Malayan-Tiger', real: 'Real')
    Animal.create(search_name: 'Maltese', image_name: 'Maltese', real: 'Real')
    Animal.create(search_name: 'Manatee', image_name: 'Manatee', real: 'Real')
    Animal.create(search_name: 'Mandrill', image_name: 'Mandrill', real: 'Real')
    Animal.create(search_name: 'Maned Wolf', image_name: 'Maned-Wolf', real: 'Real')
    Animal.create(search_name: 'Manta Ray', image_name: 'Manta-Ray', real: 'Real')
    Animal.create(search_name: 'Marine Toad', image_name: 'Marine-Toad', real: 'Real')
    Animal.create(search_name: 'Markhor', image_name: 'Markhor', real: 'Real')
    Animal.create(search_name: 'Marmot', image_name: 'Marmot', real: 'Real')
    Animal.create(search_name: 'Marsh Frog', image_name: 'Marsh-Frog', real: 'Real')
    Animal.create(search_name: 'Masked Palm Civet', image_name: 'Masked-Palm-Civet', real: 'Real')
    Animal.create(search_name: 'Mastiff', image_name: 'Mastiff', real: 'Real')
    Animal.create(search_name: 'Mayfly', image_name: 'Mayfly', real: 'Real')
    Animal.create(search_name: 'Meerkat', image_name: 'Meerkat', real: 'Real')
    Animal.create(search_name: 'Megalodon', image_name: 'Megalodon', real: 'Real')
    Animal.create(search_name: 'Mexican Free-Tailed Bat', image_name: 'Mexican-Free-Tailed-Bat', real: 'Real')
    Animal.create(search_name: 'Millipede', image_name: 'Millipede', real: 'Real')
    Animal.create(search_name: 'Mink', image_name: 'Mink', real: 'Real')
    Animal.create(search_name: 'Minke Whale', image_name: 'Minke-Whale', real: 'Real')
    Animal.create(search_name: 'Mole', image_name: 'Mole', real: 'Real')
    Animal.create(search_name: 'Molly', image_name: 'Molly', real: 'Real')
    Animal.create(search_name: 'Monarch Butterfly', image_name: 'Monarch-Butterfly', real: 'Real')
    Animal.create(search_name: 'Mongoose', image_name: 'Mongoose', real: 'Real')
    Animal.create(search_name: 'Mongrel', image_name: 'Mongrel', real: 'Real')
    Animal.create(search_name: 'Monitor Lizard', image_name: 'Monitor-Lizard', real: 'Real')
    Animal.create(search_name: 'Monkey', image_name: 'Monkey', real: 'Real')
    Animal.create(search_name: 'Monkfish', image_name: 'Monkfish', real: 'Real')
    Animal.create(search_name: 'Monte Iberia Eleuth', image_name: 'Monte-Iberia-Eleuth', real: 'Real')
    Animal.create(search_name: 'Moorhen', image_name: 'Moorhen', real: 'Real')
    Animal.create(search_name: 'Moose', image_name: 'Moose', real: 'Real')
    Animal.create(search_name: 'Moray Eel', image_name: 'Moray-Eel', real: 'Real')
    Animal.create(search_name: 'Moth', image_name: 'Moth', real: 'Real')
    Animal.create(search_name: 'Mountain Gorilla', image_name: 'Mountain-Gorilla', real: 'Real')
    Animal.create(search_name: 'Mountain Lion', image_name: 'Mountain-Lion', real: 'Real')
    Animal.create(search_name: 'Mouse', image_name: 'Mouse', real: 'Real')
    Animal.create(search_name: 'Mule', image_name: 'Mule', real: 'Real')
    Animal.create(search_name: 'Muskrat', image_name: 'Muskrat', real: 'Real')
    Animal.create(search_name: 'Nabarlek', image_name: 'Nabarlek', real: 'Real')
    Animal.create(search_name: 'Nalolo', image_name: 'Nalolo', real: 'Real')
    Animal.create(search_name: 'Nandu', image_name: 'Nandu', real: 'Real')
    Animal.create(search_name: 'Napu', image_name: 'Napu', real: 'Real')
    Animal.create(search_name: 'Narwhal', image_name: 'Narwhal', real: 'Real')
    Animal.create(search_name: 'Nase', image_name: 'Nase', real: 'Real')
    Animal.create(search_name: 'Natterjack', image_name: 'Natterjack', real: 'Real')
    Animal.create(search_name: 'Nautilus', image_name: 'Nautilus', real: 'Real')
    Animal.create(search_name: 'Neapolitan Mastiff', image_name: 'Neapolitan-Mastiff', real: 'Real')
    Animal.create(search_name: 'Neddicky', image_name: 'Neddicky', real: 'Real')
    Animal.create(search_name: 'Needlefish', image_name: 'Needlefish', real: 'Real')
    Animal.create(search_name: 'Nematode', image_name: 'Nematode', real: 'Real')
    Animal.create(search_name: 'Nënë', image_name: 'Nënë', real: 'Real')
    Animal.create(search_name: 'Newfoundland', image_name: 'Newfoundland', real: 'Real')
    Animal.create(search_name: 'Newt', image_name: 'Newt', real: 'Real')
    Animal.create(search_name: 'Nicator', image_name: 'Nicator', real: 'Real')
    Animal.create(search_name: 'Nightcrawler', image_name: 'Nightcrawler', real: 'Real')
    Animal.create(search_name: 'Nightfish', image_name: 'Nightfish', real: 'Real')
    Animal.create(search_name: 'Nightingale', image_name: 'Nightingale', real: 'Real')
    Animal.create(search_name: 'Nighthawk', image_name: 'Nighthawk', real: 'Real')
    Animal.create(search_name: 'Nightjar', image_name: 'Nightjar', real: 'Real')
    Animal.create(search_name: 'Nile Crocodile', image_name: 'Nile-Crocodile', real: 'Real')
    Animal.create(search_name: 'Nilgai', image_name: 'Nilgai', real: 'Real')
    Animal.create(search_name: 'Ningaui', image_name: 'Ningaui', real: 'Real')
    Animal.create(search_name: 'Nkupe', image_name: 'Nkupe', real: 'Real')
    Animal.create(search_name: 'Noctule', image_name: 'Noctule', real: 'Real')
    Animal.create(search_name: 'Noddy', image_name: 'Noddy', real: 'Real')
    Animal.create(search_name: 'Noodlefish', image_name: 'Noodlefish', real: 'Real')
    Animal.create(search_name: 'Norfolk Terrier', image_name: 'Norfolk-Terrier', real: 'Real')
    Animal.create(search_name: 'North American Black Bear', image_name: 'North-American-Black-Bear', real: 'Real')
    Animal.create(search_name: 'Northern Inuit Dog', image_name: 'Northern-Inuit-Dog', real: 'Real')
    Animal.create(search_name: 'Norwegian Forest', image_name: 'Norwegian-Forest', real: 'Real')
    Animal.create(search_name: 'Nudibranch', image_name: 'Nudibranch', real: 'Real')
    Animal.create(search_name: 'Numbat', image_name: 'Numbat', real: 'Real')
    Animal.create(search_name: 'Numbray', image_name: 'Numbray', real: 'Real')
    Animal.create(search_name: 'Nunbird', image_name: 'Nunbird', real: 'Real')
    Animal.create(search_name: 'Nunlet', image_name: 'Nunlet', real: 'Real')
    Animal.create(search_name: 'Nurseryfish', image_name: 'Nurseryfish', real: 'Real')
    Animal.create(search_name: 'Nurse Shark', image_name: 'Nurse-Shark', real: 'Real')
    Animal.create(search_name: 'Nutria', image_name: 'Nutria', real: 'Real')
    Animal.create(search_name: 'Nyala', image_name: 'Nyala', real: 'Real')
    Animal.create(search_name: 'Oarfish', image_name: 'Oarfish', real: 'Real')
    Animal.create(search_name: 'Ocellaris Clownfish', image_name: 'Ocellaris-Clownfish', real: 'Real')
    Animal.create(search_name: 'Ocelot', image_name: 'Ocelot', real: 'Real')
    Animal.create(search_name: 'Octopus', image_name: 'Octopus', real: 'Real')
    Animal.create(search_name: 'Oilbird', image_name: 'Oilbird', real: 'Real')
    Animal.create(search_name: 'Okapi', image_name: 'Okapi', real: 'Real')
    Animal.create(search_name: 'Old English Sheepdog', image_name: 'Old-English-Sheepdog', real: 'Real')
    Animal.create(search_name: 'Olive Ridley Sea Turtle', image_name: 'Olive-Ridley-Sea-Turtle', real: 'Real')
    Animal.create(search_name: 'Olm', image_name: 'Olm', real: 'Real')
    Animal.create(search_name: 'Opossum', image_name: 'Opossum', real: 'Real')
    Animal.create(search_name: 'Orangutan', image_name: 'Orangutan', real: 'Real')
    Animal.create(search_name: 'Orb Weaver', image_name: 'Orb-Weaver', real: 'Real')
    Animal.create(search_name: 'Orca', image_name: 'Orca', real: 'Real')
    Animal.create(search_name: 'Oriole', image_name: 'Oriole', real: 'Real')
    Animal.create(search_name: 'Ornate Chorus Frog', image_name: 'Ornate-Chorus-Frog', real: 'Real')
    Animal.create(search_name: 'Ornate Hawk-Eagle', image_name: 'Ornate-Hawk-Eagle', real: 'Real')
    Animal.create(search_name: 'Oryx', image_name: 'Oryx', real: 'Real')
    Animal.create(search_name: 'Osprey', image_name: 'Osprey', real: 'Real')
    Animal.create(search_name: 'Ostrich', image_name: 'Ostrich', real: 'Real')
    Animal.create(search_name: 'Otter', image_name: 'Otter', real: 'Real')
    Animal.create(search_name: 'Owl', image_name: 'Owl', real: 'Real')
    Animal.create(search_name: 'Owl Butterfly', image_name: 'Owl-Butterfly', real: 'Real')
    Animal.create(search_name: 'Ox', image_name: 'Ox', real: 'Real')
    Animal.create(search_name: 'Oyster', image_name: 'Oyster', real: 'Real')
    Animal.create(search_name: 'Oystercatcher', image_name: 'Oystercatcher', real: 'Real')
    Animal.create(search_name: 'Paddlefish', image_name: 'Paddlefish', real: 'Real')
    Animal.create(search_name: 'Pademelon', image_name: 'Pademelon', real: 'Real')
    Animal.create(search_name: 'Pangolin', image_name: 'Pangolin', real: 'Real')
    Animal.create(search_name: 'Panther', image_name: 'Panther', real: 'Real')
    Animal.create(search_name: 'Parrot', image_name: 'Parrot', real: 'Real')
    Animal.create(search_name: 'Patas Monkey', image_name: 'Patas-Monkey', real: 'Real')
    Animal.create(search_name: 'Peacock', image_name: 'Peacock', real: 'Real')
    Animal.create(search_name: 'Pekingese', image_name: 'Pekingese', real: 'Real')
    Animal.create(search_name: 'Pelican', image_name: 'Pelican', real: 'Real')
    Animal.create(search_name: 'Penguin', image_name: 'Penguin', real: 'Real')
    Animal.create(search_name: 'Pere David’s Deer', image_name: 'Pere-David’s-Deer', real: 'Real')
    Animal.create(search_name: 'Peregrine Falcon', image_name: 'Peregrine-Falcon', real: 'Real')
    Animal.create(search_name: 'Persian', image_name: 'Persian', real: 'Real')
    Animal.create(search_name: 'Petit Basset Griffon Vendéen', image_name: 'Petit-Basset-Griffon-Vendéen', real: 'Real')
    Animal.create(search_name: 'Pheasant', image_name: 'Pheasant', real: 'Real')
    Animal.create(search_name: 'Pied Tamarin', image_name: 'Pied-Tamarin', real: 'Real')
    Animal.create(search_name: 'Pig', image_name: 'Pig', real: 'Real')
    Animal.create(search_name: 'Pika', image_name: 'Pika', real: 'Real')
    Animal.create(search_name: 'Pike Fish', image_name: 'Pike-Fish', real: 'Real')
    Animal.create(search_name: 'Pink Fairy Armadillo', image_name: 'Pink-Fairy-Armadillo', real: 'Real')
    Animal.create(search_name: 'Piranha', image_name: 'Piranha', real: 'Real')
    Animal.create(search_name: 'Platypus', image_name: 'Platypus', real: 'Real')
    Animal.create(search_name: 'Pointer', image_name: 'Pointer', real: 'Real')
    Animal.create(search_name: 'Poison Dart Frog', image_name: 'Poison-Dart-Frog', real: 'Real')
    Animal.create(search_name: 'Polar Bear', image_name: 'Polar-Bear', real: 'Real')
    Animal.create(search_name: 'Pond Skater', image_name: 'Pond-Skater', real: 'Real')
    Animal.create(search_name: 'Poodle', image_name: 'Poodle', real: 'Real')
    Animal.create(search_name: 'Pool Frog', image_name: 'Pool-Frog', real: 'Real')
    Animal.create(search_name: 'Porcupine', image_name: 'Porcupine', real: 'Real')
    Animal.create(search_name: 'Porpoise', image_name: 'Porpoise', real: 'Real')
    Animal.create(search_name: 'Possum', image_name: 'Possum', real: 'Real')
    Animal.create(search_name: 'Prawn', image_name: 'Prawn', real: 'Real')
    Animal.create(search_name: 'Proboscis Monkey', image_name: 'Proboscis-Monkey', real: 'Real')
    Animal.create(search_name: 'Pufferfish', image_name: 'Pufferfish', real: 'Real')
    Animal.create(search_name: 'Puffin', image_name: 'Puffin', real: 'Real')
    Animal.create(search_name: 'Pug', image_name: 'Pug', real: 'Real')
    Animal.create(search_name: 'Puma', image_name: 'Puma', real: 'Real')
    Animal.create(search_name: 'Purple Emperor Butterfly', image_name: 'Purple-Emperor-Butterfly', real: 'Real')
    Animal.create(search_name: 'Puss Moth', image_name: 'Puss-Moth', real: 'Real')
    Animal.create(search_name: 'Pygmy Hippopotamus', image_name: 'Pygmy-Hippopotamus', real: 'Real')
    Animal.create(search_name: 'Pygmy Marmoset', image_name: 'Pygmy-Marmoset', real: 'Real')
    Animal.create(search_name: 'Qinling Panda', image_name: 'Qinling-Panda', real: 'Real')
    Animal.create(search_name: 'Quagga', image_name: 'Quagga', real: 'Real')
    Animal.create(search_name: 'Quahog', image_name: 'Quahog', real: 'Real')
    Animal.create(search_name: 'Quail', image_name: 'Quail', real: 'Real')
    Animal.create(search_name: 'Quaira Spiny Rat', image_name: 'Quaira-Spiny-Rat', real: 'Real')
    Animal.create(search_name: 'Quechuan Hocicudo', image_name: 'Quechuan-Hocicudo', real: 'Real')
    Animal.create(search_name: 'Queen Alexandra’s Birdwing', image_name: 'Queen-Alexandra’s-Birdwing', real: 'Real')
    Animal.create(search_name: 'Queen Angelfish', image_name: 'Queen-Angelfish', real: 'Real')
    Animal.create(search_name: 'Queen of Sheba’s Gazelle', image_name: 'Queen-of-Sheba’s-Gazelle', real: 'Real')
    Animal.create(search_name: 'Queen Snake', image_name: 'Queen-Snake', real: 'Real')
    Animal.create(search_name: 'Queen Snapper', image_name: 'Queen-Snapper', real: 'Real')
    Animal.create(search_name: 'Queen Triggerfish', image_name: 'Queen-Triggerfish', real: 'Real')
    Animal.create(search_name: 'Queensland Grouper', image_name: 'Queensland-Grouper', real: 'Real')
    Animal.create(search_name: 'Queensland Tube-Nosed Bat', image_name: 'Queensland-Tube-Nosed-Bat', real: 'Real')
    Animal.create(search_name: 'Quelea', image_name: 'Quelea', real: 'Real')
    Animal.create(search_name: 'Quetzal', image_name: 'Quetzal', real: 'Real')
    Animal.create(search_name: 'Quokka', image_name: 'Quokka', real: 'Real')
    Animal.create(search_name: 'Quoll', image_name: 'Quoll', real: 'Real')
    Animal.create(search_name: 'Rabbit', image_name: 'Rabbit', real: 'Real')
    Animal.create(search_name: 'Racoon', image_name: 'Racoon', real: 'Real')
    Animal.create(search_name: 'Racoon Dog', image_name: 'Racoon-Dog', real: 'Real')
    Animal.create(search_name: 'Radiated Tortoise', image_name: 'Radiated-Tortoise', real: 'Real')
    Animal.create(search_name: 'Ragdoll', image_name: 'Ragdoll', real: 'Real')
    Animal.create(search_name: 'Rat', image_name: 'Rat', real: 'Real')
    Animal.create(search_name: 'Rattlesnake', image_name: 'Rattlesnake', real: 'Real')
    Animal.create(search_name: 'Red Finch', image_name: 'Red-Finch', real: 'Real')
    Animal.create(search_name: 'Red Fox', image_name: 'Red-Fox', real: 'Real')
    Animal.create(search_name: 'Red Knee Tarantula', image_name: 'Red-Knee-Tarantula', real: 'Real')
    Animal.create(search_name: 'Red Panda', image_name: 'Red-Panda', real: 'Real')
    Animal.create(search_name: 'Red Wolf', image_name: 'Red-Wolf', real: 'Real')
    Animal.create(search_name: 'Red-handed Tamarin', image_name: 'Red-handed-Tamarin', real: 'Real')
    Animal.create(search_name: 'Reindeer', image_name: 'Reindeer', real: 'Real')
    Animal.create(search_name: 'Rhinoceros', image_name: 'Rhinoceros', real: 'Real')
    Animal.create(search_name: 'River Turtle', image_name: 'River-Turtle', real: 'Real')
    Animal.create(search_name: 'Robin', image_name: 'Robin', real: 'Real')
    Animal.create(search_name: 'Rock Hyrax', image_name: 'Rock-Hyrax', real: 'Real')
    Animal.create(search_name: 'Rockfish', image_name: 'Rockfish', real: 'Real')
    Animal.create(search_name: 'Rockhopper Penguin', image_name: 'Rockhopper-Penguin', real: 'Real')
    Animal.create(search_name: 'Roseate Spoonbill', image_name: 'Roseate-Spoonbill', real: 'Real')
    Animal.create(search_name: 'Rottweiler', image_name: 'Rottweiler', real: 'Real')
    Animal.create(search_name: 'Royal Penguin', image_name: 'Royal-Penguin', real: 'Real')
    Animal.create(search_name: 'Russian Blue', image_name: 'Russian-Blue', real: 'Real')
    Animal.create(search_name: 'Saarloos Wolfdog', image_name: 'Saarloos-Wolfdog', real: 'Real')
    Animal.create(search_name: 'Saiga', image_name: 'Saiga', real: 'Real')
    Animal.create(search_name: 'Saint Bernard', image_name: 'Saint-Bernard', real: 'Real')
    Animal.create(search_name: 'Salamander', image_name: 'Salamander', real: 'Real')
    Animal.create(search_name: 'Salmon', image_name: 'Salmon', real: 'Real')
    Animal.create(search_name: 'Samoyed', image_name: 'Samoyed', real: 'Real')
    Animal.create(search_name: 'Sand Lizard', image_name: 'Sand-Lizard', real: 'Real')
    Animal.create(search_name: 'Saola', image_name: 'Saola', real: 'Real')
    Animal.create(search_name: 'Sardines', image_name: 'Sardines', real: 'Real')
    Animal.create(search_name: 'Sawfish', image_name: 'Sawfish', real: 'Real')
    Animal.create(search_name: 'Scorpion', image_name: 'Scorpion', real: 'Real')
    Animal.create(search_name: 'Scorpion Fish', image_name: 'Scorpion-Fish', real: 'Real')
    Animal.create(search_name: 'Sea Dragon', image_name: 'Sea-Dragon', real: 'Real')
    Animal.create(search_name: 'Sea Lion', image_name: 'Sea-Lion', real: 'Real')
    Animal.create(search_name: 'Sea Otter', image_name: 'Sea-Otter', real: 'Real')
    Animal.create(search_name: 'Sea Slug', image_name: 'Sea-Slug', real: 'Real')
    Animal.create(search_name: 'Sea Squirt', image_name: 'Sea-Squirt', real: 'Real')
    Animal.create(search_name: 'Sea Turtle', image_name: 'Sea-Turtle', real: 'Real')
    Animal.create(search_name: 'Sea Urchin', image_name: 'Sea-Urchin', real: 'Real')
    Animal.create(search_name: 'Seahorse', image_name: 'Seahorse', real: 'Real')
    Animal.create(search_name: 'Seal', image_name: 'Seal', real: 'Real')
    Animal.create(search_name: 'Serval', image_name: 'Serval', real: 'Real')
    Animal.create(search_name: 'Shark', image_name: 'Shark', real: 'Real')
    Animal.create(search_name: 'Sheep', image_name: 'Sheep', real: 'Real')
    Animal.create(search_name: 'Shiba Inu', image_name: 'Shiba-Inu', real: 'Real')
    Animal.create(search_name: 'Shih Tzu', image_name: 'Shih-Tzu', real: 'Real')
    Animal.create(search_name: 'Shrimp', image_name: 'Shrimp', real: 'Real')
    Animal.create(search_name: 'Siamese', image_name: 'Siamese', real: 'Real')
    Animal.create(search_name: 'Siamese Fighting Fish', image_name: 'Siamese-Fighting-Fish', real: 'Real')
    Animal.create(search_name: 'Siberian Cat', image_name: 'Siberian-Cat', real: 'Real')
    Animal.create(search_name: 'Siberian Husky', image_name: 'Siberian-Husky', real: 'Real')
    Animal.create(search_name: 'Siberian Tiger', image_name: 'Siberian-Tiger', real: 'Real')
    Animal.create(search_name: 'Silver Dollar', image_name: 'Silver-Dollar', real: 'Real')
    Animal.create(search_name: 'Skate Fish', image_name: 'Skate-Fish', real: 'Real')
    Animal.create(search_name: 'Skunk', image_name: 'Skunk', real: 'Real')
    Animal.create(search_name: 'Sloth', image_name: 'Sloth', real: 'Real')
    Animal.create(search_name: 'Slow Worm', image_name: 'Slow-Worm', real: 'Real')
    Animal.create(search_name: 'Snail', image_name: 'Snail', real: 'Real')
    Animal.create(search_name: 'Snake', image_name: 'Snake', real: 'Real')
    Animal.create(search_name: 'Snapping Turtle', image_name: 'Snapping-Turtle', real: 'Real')
    Animal.create(search_name: 'Snowshoe Hare', image_name: 'Snowshoe-Hare', real: 'Real')
    Animal.create(search_name: 'Snowy Owl', image_name: 'Snowy-Owl', real: 'Real')
    Animal.create(search_name: 'South China Tiger', image_name: 'South-China-Tiger', real: 'Real')
    Animal.create(search_name: 'Spadefoot Toad', image_name: 'Spadefoot-Toad', real: 'Real')
    Animal.create(search_name: 'Sparrow', image_name: 'Sparrow', real: 'Real')
    Animal.create(search_name: 'Spectacled Bear', image_name: 'Spectacled-Bear', real: 'Real')
    Animal.create(search_name: 'Sperm Whale', image_name: 'Sperm-Whale', real: 'Real')
    Animal.create(search_name: 'Spider Monkey', image_name: 'Spider-Monkey', real: 'Real')
    Animal.create(search_name: 'Spiny Dogfish', image_name: 'Spiny-Dogfish', real: 'Real')
    Animal.create(search_name: 'Spix’s Macaw', image_name: 'Spix’s-Macaw', real: 'Real')
    Animal.create(search_name: 'Sponge', image_name: 'Sponge', real: 'Real')
    Animal.create(search_name: 'Squid', image_name: 'Squid', real: 'Real')
    Animal.create(search_name: 'Squirrel', image_name: 'Squirrel', real: 'Real')
    Animal.create(search_name: 'Squirrel Monkey', image_name: 'Squirrel-Monkey', real: 'Real')
    Animal.create(search_name: 'Sri Lankan Elephant', image_name: 'Sri-Lankan-Elephant', real: 'Real')
    Animal.create(search_name: 'Staffordshire Bull Terrier', image_name: 'Staffordshire-Bull-Terrier', real: 'Real')
    Animal.create(search_name: 'Stag Beetle', image_name: 'Stag-Beetle', real: 'Real')
    Animal.create(search_name: 'Starfish', image_name: 'Starfish', real: 'Real')
    Animal.create(search_name: 'Stick Insect', image_name: 'Stick-Insect', real: 'Real')
    Animal.create(search_name: 'Stingray', image_name: 'Stingray', real: 'Real')
    Animal.create(search_name: 'Stoat', image_name: 'Stoat', real: 'Real')
    Animal.create(search_name: 'Striped Rocket Frog', image_name: 'Striped-Rocket-Frog', real: 'Real')
    Animal.create(search_name: 'Sturgeon', image_name: 'Sturgeon', real: 'Real')
    Animal.create(search_name: 'Sucker Fish', image_name: 'Sucker-Fish', real: 'Real')
    Animal.create(search_name: 'Sumatran Elephant', image_name: 'Sumatran-Elephant', real: 'Real')
    Animal.create(search_name: 'Sumatran Orangutan', image_name: 'Sumatran-Orangutan', real: 'Real')
    Animal.create(search_name: 'Sumatran Rhinoceros', image_name: 'Sumatran-Rhinoceros', real: 'Real')
    Animal.create(search_name: 'Sumatran Tiger', image_name: 'Sumatran-Tiger', real: 'Real')
    Animal.create(search_name: 'Sun Bear', image_name: 'Sun-Bear', real: 'Real')
    Animal.create(search_name: 'Swai Fish', image_name: 'Swai-Fish', real: 'Real')
    Animal.create(search_name: 'Swan', image_name: 'Swan', real: 'Real')
    Animal.create(search_name: 'Swedish Vallhund', image_name: 'Swedish-Vallhund', real: 'Real')
    Animal.create(search_name: 'Taipan', image_name: 'Taipan', real: 'Real')
    Animal.create(search_name: 'Takin', image_name: 'Takin', real: 'Real')
    Animal.create(search_name: 'Tamaskan', image_name: 'Tamaskan', real: 'Real')
    Animal.create(search_name: 'Tang', image_name: 'Tang', real: 'Real')
    Animal.create(search_name: 'Tapanuli Orangutan', image_name: 'Tapanuli-Orangutan', real: 'Real')
    Animal.create(search_name: 'Tapir', image_name: 'Tapir', real: 'Real')
    Animal.create(search_name: 'Tarantula', image_name: 'Tarantula', real: 'Real')
    Animal.create(search_name: 'Tarpon', image_name: 'Tarpon', real: 'Real')
    Animal.create(search_name: 'Tarsier', image_name: 'Tarsier', real: 'Real')
    Animal.create(search_name: 'Tasmanian Devil', image_name: 'Tasmanian-Devil', real: 'Real')
    Animal.create(search_name: 'Tawny Owl', image_name: 'Tawny-Owl', real: 'Real')
    Animal.create(search_name: 'Teddy Roosevelt Terrier', image_name: 'Teddy-Roosevelt-Terrier', real: 'Real')
    Animal.create(search_name: 'Termite', image_name: 'Termite', real: 'Real')
    Animal.create(search_name: 'Tetra', image_name: 'Tetra', real: 'Real')
    Animal.create(search_name: 'Thorny Devil', image_name: 'Thorny-Devil', real: 'Real')
    Animal.create(search_name: 'Tibetan Mastiff', image_name: 'Tibetan-Mastiff', real: 'Real')
    Animal.create(search_name: 'Tick', image_name: 'Tick', real: 'Real')
    Animal.create(search_name: 'Tiffany', image_name: 'Tiffany', real: 'Real')
    Animal.create(search_name: 'Tiger', image_name: 'Tiger', real: 'Real')
    Animal.create(search_name: 'Tiger Beetle', image_name: 'Tiger-Beetle', real: 'Real')
    Animal.create(search_name: 'Tiger Salamander', image_name: 'Tiger-Salamander', real: 'Real')
    Animal.create(search_name: 'Tiger Shark', image_name: 'Tiger-Shark', real: 'Real')
    Animal.create(search_name: 'Tiger Snake', image_name: 'Tiger-Snake', real: 'Real')
    Animal.create(search_name: 'Timber Rattlesnake', image_name: 'Timber-Rattlesnake', real: 'Real')
    Animal.create(search_name: 'Titmouse', image_name: 'Titmouse', real: 'Real')
    Animal.create(search_name: 'Toad', image_name: 'Toad', real: 'Real')
    Animal.create(search_name: 'Tortoise', image_name: 'Tortoise', real: 'Real')
    Animal.create(search_name: 'Toucan', image_name: 'Toucan', real: 'Real')
    Animal.create(search_name: 'Tree Frog', image_name: 'Tree-Frog', real: 'Real')
    Animal.create(search_name: 'Tree Kangaroo', image_name: 'Tree-Kangaroo', real: 'Real')
    Animal.create(search_name: 'Triggerfish', image_name: 'Triggerfish', real: 'Real')
    Animal.create(search_name: 'Tropicbird', image_name: 'Tropicbird', real: 'Real')
    Animal.create(search_name: 'Trout', image_name: 'Trout', real: 'Real')
    Animal.create(search_name: 'Tuatara', image_name: 'Tuatara', real: 'Real')
    Animal.create(search_name: 'Tuna', image_name: 'Tuna', real: 'Real')
    Animal.create(search_name: 'Tundra Swan', image_name: 'Tundra-Swan', real: 'Real')
    Animal.create(search_name: 'Tur', image_name: 'Tur', real: 'Real')
    Animal.create(search_name: 'Turkey', image_name: 'Turkey', real: 'Real')
    Animal.create(search_name: 'Turkey Vulture', image_name: 'Turkey-Vulture', real: 'Real')
    Animal.create(search_name: 'Turkish Angora', image_name: 'Turkish-Angora', real: 'Real')
    Animal.create(search_name: 'Turtle', image_name: 'Turtle', real: 'Real')
    Animal.create(search_name: 'Turtle Dove', image_name: 'Turtle-Dove', real: 'Real')
    Animal.create(search_name: 'Uakari', image_name: 'Uakari', real: 'Real')
    Animal.create(search_name: 'Uganda Kob', image_name: 'Uganda-Kob', real: 'Real')
    Animal.create(search_name: 'Uguisu', image_name: 'Uguisu', real: 'Real')
    Animal.create(search_name: 'Uinta Chipmunk', image_name: 'Uinta-Chipmunk', real: 'Real')
    Animal.create(search_name: 'Uinta Ground Squirrel', image_name: 'Uinta-Ground-Squirrel', real: 'Real')
    Animal.create(search_name: 'Ulysses Butterfly', image_name: 'Ulysses-Butterfly', real: 'Real')
    Animal.create(search_name: 'Umbrella Bird', image_name: 'Umbrella-Bird', real: 'Real')
    Animal.create(search_name: 'Unau', image_name: 'Unau', real: 'Real')
    Animal.create(search_name: 'Unicornfish', image_name: 'Unicornfish', real: 'Real')
    Animal.create(search_name: 'Upupa', image_name: 'Upupa', real: 'Real')
    Animal.create(search_name: 'Urchin', image_name: 'Urchin', real: 'Real')
    Animal.create(search_name: 'Urial', image_name: 'Urial', real: 'Real')
    Animal.create(search_name: 'Uromastyx', image_name: 'Uromastyx', real: 'Real')
    Animal.create(search_name: 'Urraca', image_name: 'Urraca', real: 'Real')
    Animal.create(search_name: 'Vampire Bat', image_name: 'Vampire-Bat', real: 'Real')
    Animal.create(search_name: 'Vampire Squid', image_name: 'Vampire-Squid', real: 'Real')
    Animal.create(search_name: 'Vancouver Island Marmot', image_name: 'Vancouver-Island-Marmot', real: 'Real')
    Animal.create(search_name: 'Vanga', image_name: 'Vanga', real: 'Real')
    Animal.create(search_name: 'Vaquita', image_name: 'Vaquita', real: 'Real')
    Animal.create(search_name: 'Variegated Squirrel', image_name: 'Variegated-Squirrel', real: 'Real')
    Animal.create(search_name: 'Velvet Asity', image_name: 'Velvet-Asity', real: 'Real')
    Animal.create(search_name: 'Verreaux’s Sifaka', image_name: 'Verreaux’s-Sifaka', real: 'Real')
    Animal.create(search_name: 'Vervet Monkey', image_name: 'Vervet-Monkey', real: 'Real')
    Animal.create(search_name: 'Vicuña', image_name: 'Vicuña', real: 'Real')
    Animal.create(search_name: 'Viper', image_name: 'Viper', real: 'Real')
    Animal.create(search_name: 'Viperfish', image_name: 'Viperfish', real: 'Real')
    Animal.create(search_name: 'Vireo', image_name: 'Vireo', real: 'Real')
    Animal.create(search_name: 'Virginia Opossum', image_name: 'Virginia-Opossum', real: 'Real')
    Animal.create(search_name: 'Visayan Spotted Deer', image_name: 'Visayan-Spotted-Deer', real: 'Real')
    Animal.create(search_name: 'Visayan Warty Pig', image_name: 'Visayan-Warty-Pig', real: 'Real')
    Animal.create(search_name: 'Vlei Rat', image_name: 'Vlei-Rat', real: 'Real')
    Animal.create(search_name: 'Volcano Rabbit', image_name: 'Volcano-Rabbit', real: 'Real')
    Animal.create(search_name: 'Vole', image_name: 'Vole', real: 'Real')
    Animal.create(search_name: 'Vulture', image_name: 'Vulture', real: 'Real')
    Animal.create(search_name: 'Wallaby', image_name: 'Wallaby', real: 'Real')
    Animal.create(search_name: 'Walleye Fish', image_name: 'Walleye-Fish', real: 'Real')
    Animal.create(search_name: 'Walrus', image_name: 'Walrus', real: 'Real')
    Animal.create(search_name: 'Wandering Albatross', image_name: 'Wandering-Albatross', real: 'Real')
    Animal.create(search_name: 'Warthog', image_name: 'Warthog', real: 'Real')
    Animal.create(search_name: 'Wasp', image_name: 'Wasp', real: 'Real')
    Animal.create(search_name: 'Water Buffalo', image_name: 'Water-Buffalo', real: 'Real')
    Animal.create(search_name: 'Water Dragon', image_name: 'Water-Dragon', real: 'Real')
    Animal.create(search_name: 'Water Vole', image_name: 'Water-Vole', real: 'Real')
    Animal.create(search_name: 'Weasel', image_name: 'Weasel', real: 'Real')
    Animal.create(search_name: 'Welsh Corgi', image_name: 'Welsh-Corgi', real: 'Real')
    Animal.create(search_name: 'West Highland Terrier', image_name: 'West-Highland-Terrier', real: 'Real')
    Animal.create(search_name: 'Western Lowland Gorilla', image_name: 'Western-Lowland-Gorilla', real: 'Real')
    Animal.create(search_name: 'Whale Shark', image_name: 'Whale-Shark', real: 'Real')
    Animal.create(search_name: 'Whippet', image_name: 'Whippet', real: 'Real')
    Animal.create(search_name: 'White Hawk', image_name: 'White-Hawk', real: 'Real')
    Animal.create(search_name: 'White Rhinoceros', image_name: 'White-Rhinoceros', real: 'Real')
    Animal.create(search_name: 'White Tiger', image_name: 'White-Tiger', real: 'Real')
    Animal.create(search_name: 'White-Faced Capuchin', image_name: 'White-Faced-Capuchin', real: 'Real')
    Animal.create(search_name: 'Wild Boar', image_name: 'Wild-Boar', real: 'Real')
    Animal.create(search_name: 'Wild Horse', image_name: 'Wild-Horse', real: 'Real')
    Animal.create(search_name: 'Wild Turkey', image_name: 'Wild-Turkey', real: 'Real')
    Animal.create(search_name: 'Wildebeest', image_name: 'Wildebeest', real: 'Real')
    Animal.create(search_name: 'Wolf', image_name: 'Wolf', real: 'Real')
    Animal.create(search_name: 'Wolf Eel', image_name: 'Wolf-Eel', real: 'Real')
    Animal.create(search_name: 'Wolf Spider', image_name: 'Wolf-Spider', real: 'Real')
    Animal.create(search_name: 'Wolffish', image_name: 'Wolffish', real: 'Real')
    Animal.create(search_name: 'Wolverine', image_name: 'Wolverine', real: 'Real')
    Animal.create(search_name: 'Wombat', image_name: 'Wombat', real: 'Real')
    Animal.create(search_name: 'Woodlouse', image_name: 'Woodlouse', real: 'Real')
    Animal.create(search_name: 'Woodpecker', image_name: 'Woodpecker', real: 'Real')
    Animal.create(search_name: 'Woolly Mammoth', image_name: 'Woolly-Mammoth', real: 'Real')
    Animal.create(search_name: 'Woolly Monkey', image_name: 'Woolly-Monkey', real: 'Real')
    Animal.create(search_name: 'Wrasse', image_name: 'Wrasse', real: 'Real')
    Animal.create(search_name: 'Wyoming Toad', image_name: 'Wyoming-Toad', real: 'Real')
    Animal.create(search_name: 'X-Ray Tetra', image_name: 'X-Ray-Tetra', real: 'Real')
    Animal.create(search_name: 'Xantic Sargo', image_name: 'Xantic-Sargo', real: 'Real')
    Animal.create(search_name: 'Xantus’s Hummingbird', image_name: 'Xantus’s-Hummingbird', real: 'Real')
    Animal.create(search_name: 'Xantus Murrelet', image_name: 'Xantus-Murrelet', real: 'Real')
    Animal.create(search_name: 'Xenarthra', image_name: 'Xenarthra', real: 'Real')
    Animal.create(search_name: 'Xenopoecilus ', image_name: 'Xenopoecilus-', real: 'Real')
    Animal.create(search_name: 'Xenops', image_name: 'Xenops', real: 'Real')
    Animal.create(search_name: 'Xerus', image_name: 'Xerus', real: 'Real')
    Animal.create(search_name: 'Xingu River Ray', image_name: 'Xingu-River-Ray', real: 'Real')
    Animal.create(search_name: 'Xolmis', image_name: 'Xolmis', real: 'Real')
    Animal.create(search_name: 'Xoloitzcuintli', image_name: 'Xoloitzcuintli', real: 'Real')
    Animal.create(search_name: 'Yabby', image_name: 'Yabby', real: 'Real')
    Animal.create(search_name: 'Yak', image_name: 'Yak', real: 'Real')
    Animal.create(search_name: 'Yellow Ground Squirrel', image_name: 'Yellow-Ground-Squirrel', real: 'Real')
    Animal.create(search_name: 'Yellow Mongoose', image_name: 'Yellow-Mongoose', real: 'Real')
    Animal.create(search_name: 'Yellow-Backed Duiker', image_name: 'Yellow-Backed-Duiker', real: 'Real')
    Animal.create(search_name: 'Yellow-Bellied Marmot', image_name: 'Yellow-Bellied-Marmot', real: 'Real')
    Animal.create(search_name: 'Yellow-Bellied Weasel', image_name: 'Yellow-Bellied-Weasel', real: 'Real')
    Animal.create(search_name: 'Yellow-Eyed Penguin', image_name: 'Yellow-Eyed-Penguin', real: 'Real')
    Animal.create(search_name: 'Yellow-Footed Antechinus', image_name: 'Yellow-Footed-Antechinus', real: 'Real')
    Animal.create(search_name: 'Yellow-Footed Rock Wallaby', image_name: 'Yellow-Footed-Rock-Wallaby', real: 'Real')
    Animal.create(search_name: 'Yellow-Necked Field Mouse', image_name: 'Yellow-Necked-Field-Mouse', real: 'Real')
    Animal.create(search_name: 'Yellow-Nosed Cotton Rat', image_name: 'Yellow-Nosed-Cotton-Rat', real: 'Real')
    Animal.create(search_name: 'Yellow-Pine Chipmunk', image_name: 'Yellow-Pine-Chipmunk', real: 'Real')
    Animal.create(search_name: 'Yellow-Throated Marten', image_name: 'Yellow-Throated-Marten', real: 'Real')
    Animal.create(search_name: 'Yellow-Winged Bat', image_name: 'Yellow-Winged-Bat', real: 'Real')
    Animal.create(search_name: 'Yucatan Squirrel', image_name: 'Yucatan-Squirrel', real: 'Real')
    Animal.create(search_name: 'Yuma Myotis', image_name: 'Yuma-Myotis', real: 'Real')
    Animal.create(search_name: 'Zapata Wren', image_name: 'Zapata-Wren', real: 'Real')
    Animal.create(search_name: 'Zebra', image_name: 'Zebra', real: 'Real')
    Animal.create(search_name: 'Zebra Duiker', image_name: 'Zebra-Duiker', real: 'Real')
    Animal.create(search_name: 'Zebra Finch', image_name: 'Zebra-Finch', real: 'Real')
    Animal.create(search_name: 'Zebrafish', image_name: 'Zebrafish', real: 'Real')
    Animal.create(search_name: 'Zebra Shark', image_name: 'Zebra-Shark', real: 'Real')
    Animal.create(search_name: 'Zebu', image_name: 'Zebu', real: 'Real')
    Animal.create(search_name: 'Zenaida Dove', image_name: 'Zenaida-Dove', real: 'Real')
    Animal.create(search_name: 'Zokor', image_name: 'Zokor', real: 'Real')
    Animal.create(search_name: 'Zone-tailed Pigeon', image_name: 'Zone-tailed-Pigeon', real: 'Real')
    Animal.create(search_name: 'Zonkey', image_name: 'Zonkey', real: 'Real')
    Animal.create(search_name: 'Zorilla', image_name: 'Zorilla', real: 'Real')
    Animal.create(search_name: 'Zorro', image_name: 'Zorro', real: 'Real')
    Animal.create(search_name: 'Zorse', image_name: 'Zorse', real: 'Real')
Animal.create(search_name: 'Goblin', image_name: 'Goblin', real: 'Imaginary', habitat: 'In the bushes on Halloween')  end
end
