namespace :load_potter do
  desc 'load animal names'
  task initialize: :environment do
	Animal.create(search_name: 'Acromantula', image_name: '/wiki/Acromantula', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Alizor of Westacottus', image_name: '/wiki/Alizor_of_Westacottus', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ashwinder', image_name: '/wiki/Ashwinder', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Augurey', image_name: '/wiki/Augurey', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Basilisk', image_name: '/wiki/Basilisk', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Bicorn', image_name: '/wiki/Bicorn', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Billywig', image_name: '/wiki/Billywig', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Blast-Ended Skrewt', image_name: '/wiki/Blast-Ended_Skrewt', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Bowtruckle', image_name: '/wiki/Bowtruckle', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Bundimun', image_name: '/wiki/Bundimun', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Centaur', image_name: '/wiki/Centaur', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chimaera', image_name: '/wiki/Chimaera', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chizpurfle', image_name: '/wiki/Chizpurfle', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chupacabra', image_name: '/wiki/Chupacabra', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Clabbert', image_name: '/wiki/Clabbert', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Coco Rumsey Catcher', image_name: '/wiki/Coco_Rumsey_Catcher', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Crup', image_name: '/wiki/Crup', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Daraliznof Freaazer', image_name: '/wiki/Daraliznof_Freaazer', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Demiguise', image_name: '/wiki/Demiguise', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Diricawl', image_name: '/wiki/Diricawl', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Double-ended Newt', image_name: '/wiki/Double-ended_Newt', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Doxy', image_name: '/wiki/Doxy', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Doxy Queen', image_name: '/wiki/Doxy_Queen', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dragon', image_name: '/wiki/Dragon', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Antipodean Opaleye dragon', image_name: '/wiki/Antipodean_Opaleye', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Catalonian Fireball dragon', image_name: '/wiki/Catalonian_Fireball', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chinese Fireball dragon', image_name: '/wiki/Chinese_Fireball', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Common Welsh Green dragon', image_name: '/wiki/Common_Welsh_Green', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hebridean Black Dragon', image_name: '/wiki/Hebridean_Black', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hungarian Horntail dragon', image_name: '/wiki/Hungarian_Horntail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Norwegian Ridgeback dragon', image_name: '/wiki/Norwegian_Ridgeback', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Peruvian Vipertooth dragon', image_name: '/wiki/Peruvian_Vipertooth', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Portuguese Long-Snout dragon', image_name: '/wiki/Portuguese_Long-Snout', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Romanian Longhorn dragon', image_name: '/wiki/Romanian_Longhorn', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Swedish Short-Snout dragon', image_name: '/wiki/Swedish_Short-Snout', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ukrainian Ironbelly dragon', image_name: '/wiki/Ukrainian_Ironbelly', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Water dragon', image_name: '/wiki/Water_dragon', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dugbog', image_name: '/wiki/Dugbog', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Erkling', image_name: '/wiki/Erkling', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Erumpent', image_name: '/wiki/Erumpent', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fairy', image_name: '/wiki/Fairy', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fire crab', image_name: '/wiki/Fire_crab', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Firedrake', image_name: '/wiki/Firedrake', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flobberworm', image_name: '/wiki/Flobberworm', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flying Seahorse', image_name: '/wiki/Flying_Seahorse', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fwooper', image_name: '/wiki/Fwooper', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ghoul', image_name: '/wiki/Ghoul', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chameleon Ghoul', image_name: '/wiki/Chameleon_Ghoul', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dung beetle', image_name: '/wiki/Dung_beetle', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Squid', image_name: '/wiki/Giant_Squid', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Glow Bug', image_name: '/wiki/Glow_Bug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Glumbumble', image_name: '/wiki/Glumbumble', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gnome', image_name: '/wiki/Gnome', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Golden Snidget', image_name: '/wiki/Golden_Snidget', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Graphorn', image_name: '/wiki/Graphorn', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Griffin', image_name: '/wiki/Griffin', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Grindylow', image_name: '/wiki/Grindylow', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gringwart Goff', image_name: '/wiki/Gringwart_Goff', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hidebehind', image_name: '/wiki/Hidebehind', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hinkypunk', image_name: '/wiki/Hinkypunk', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hippocampus', image_name: '/wiki/Hippocampus', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hippogriff', image_name: '/wiki/Hippogriff', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hodag', image_name: '/wiki/Hodag', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hoo-hoo', image_name: '/wiki/Hoo-hoo', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Horklump', image_name: '/wiki/Horklump', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Horned Serpent', image_name: '/wiki/Horned_Serpent', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Imp', image_name: '/wiki/Imp', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Imperial Dragonfly', image_name: '/wiki/Imperial_Dragonfly', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Jackalope', image_name: '/wiki/Jackalope', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Jarvey', image_name: '/wiki/Jarvey', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Jobberknoll', image_name: '/wiki/Jobberknoll', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Kappa', image_name: '/wiki/Kappa', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Kelpie', image_name: '/wiki/Kelpie', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Knarl', image_name: '/wiki/Knarl', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Kneazle', image_name: '/wiki/Kneazle', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Leprechaun', image_name: '/wiki/Leprechaun', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Lethifold', image_name: '/wiki/Lethifold', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Leucrotta', image_name: '/wiki/Leucrotta', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Limax', image_name: '/wiki/Limax', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Lobalug', image_name: '/wiki/Lobalug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Mackled Malaclaw', image_name: '/wiki/Mackled_Malaclaw', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Manticore', image_name: '/wiki/Manticore', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Marmite', image_name: '/wiki/Marmite', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Matagot', image_name: '/wiki/Matagot', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Merpeople', image_name: '/wiki/Merpeople', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Merrow', image_name: '/wiki/Merrow', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Selkie', image_name: '/wiki/Selkie', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Siren', image_name: '/wiki/Siren', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Miraf Leldendi', image_name: '/wiki/Miraf_Leldendi', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Moke', image_name: '/wiki/Moke', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Mooncalf', image_name: '/wiki/Mooncalf', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Mortis Bat', image_name: '/wiki/Mortis_Bat', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Murtlap', image_name: '/wiki/Murtlap', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Muskrill', image_name: '/wiki/Muskrill', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Nazzle Mumph', image_name: '/wiki/Nazzle_Mumph', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Niffler', image_name: '/wiki/Niffler', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Nogtail', image_name: '/wiki/Nogtail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Nundu', image_name: '/wiki/Nundu', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Occamy', image_name: '/wiki/Occamy', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Oni', image_name: '/wiki/Oni', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Phoenix', image_name: '/wiki/Phoenix', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pixie', image_name: '/wiki/Pixie', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pixie', image_name: '/wiki/Pixie', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Plague Rat', image_name: '/wiki/Plague_Rat', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Plague Rat', image_name: '/wiki/Giant_Plague_Rat', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Plimpy', image_name: '/wiki/Plimpy', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pogrebin', image_name: '/wiki/Pogrebin', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Porlock', image_name: '/wiki/Porlock', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Puffskein', image_name: '/wiki/Puffskein', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Appaloosa Puffskein', image_name: '/wiki/Appaloosa_Puffskein', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fanged Puffskein', image_name: '/wiki/Fanged_Puffskein', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pygmy Puff', image_name: '/wiki/Pygmy_Puff', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pygmy Kraken', image_name: '/wiki/Pygmy_Kraken', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Qilin', image_name: '/wiki/Qilin', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Quintaped', image_name: '/wiki/Quintaped', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ramora', image_name: '/wiki/Ramora', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Rat', image_name: '/wiki/Rat', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Rat (species)', image_name: '/wiki/Giant_Rat_(species)', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Red Cap', image_name: '/wiki/Red_Cap', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Re&#39;em', image_name: '/wiki/Re%27em', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Runespoor', image_name: '/wiki/Runespoor', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fire Dwelling Salamander', image_name: '/wiki/Fire_Dwelling_Salamander', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Amazonian Salamander', image_name: '/wiki/Amazonian_Salamander', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Blue salamander', image_name: '/wiki/Blue_salamander', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Frost Salamander', image_name: '/wiki/Frost_Salamander', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Peruvian Salamander', image_name: '/wiki/Peruvian_Salamander', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sea serpent', image_name: '/wiki/Sea_serpent', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Selma', image_name: '/wiki/Selma', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Shelliferous Drogodflikerous', image_name: '/wiki/Shelliferous_Drogodflikerous', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Shrake', image_name: '/wiki/Shrake', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Six-legged panda pig', image_name: '/wiki/Six-legged_panda_pig', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Slug', image_name: '/wiki/Slug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fire slug', image_name: '/wiki/Fire_slug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flesh-Eating Slug', image_name: '/wiki/Flesh-Eating_Slug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Horned slug', image_name: '/wiki/Horned_slug', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Snail', image_name: '/wiki/Snail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Firetrail Snail', image_name: '/wiki/Firetrail_Snail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flailtail Snail', image_name: '/wiki/Flailtail_Snail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Orange Snail', image_name: '/wiki/Giant_Orange_Snail', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Snallygaster', image_name: '/wiki/Snallygaster', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Snake', image_name: '/wiki/Snake', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fenny Snake', image_name: '/wiki/Fenny_Snake', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gigantic serpent', image_name: '/wiki/Gigantic_serpent', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Spitting snake', image_name: '/wiki/Spitting_snake', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sphinx', image_name: '/wiki/Sphinx', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Spider', image_name: '/wiki/Spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Cocoon Spider', image_name: '/wiki/Cocoon_Spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Black Spider', image_name: '/wiki/Giant_Black_Spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Spider', image_name: '/wiki/Giant_Spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Large spider', image_name: '/wiki/Large_spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Panic Spider', image_name: '/wiki/Panic_Spider', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Streeler', image_name: '/wiki/Streeler', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Swooping Evil', image_name: '/wiki/Swooping_Evil', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Tebo', image_name: '/wiki/Tebo', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Three-Headed Dog', image_name: '/wiki/Three-Headed_Dog', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Thunderbird', image_name: '/wiki/Thunderbird', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Toad', image_name: '/wiki/Toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Briar Toad', image_name: '/wiki/Briar_Toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dragon toad', image_name: '/wiki/Dragon_toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Purple Toad', image_name: '/wiki/Giant_Purple_Toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Three toed tree toad', image_name: '/wiki/Three_toed_tree_toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wide-mouth toad', image_name: '/wiki/Wide-mouth_toad', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Troll', image_name: '/wiki/Troll', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Forest Troll', image_name: '/wiki/Forest_Troll', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Mountain Troll', image_name: '/wiki/Mountain_Troll', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'River Troll', image_name: '/wiki/River_Troll', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Troll of Nadroj', image_name: '/wiki/Troll_of_Nadroj', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Trollcleg', image_name: '/wiki/Trollcleg', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Trollwig', image_name: '/wiki/Trollwig', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Unicorn', image_name: '/wiki/Unicorn', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Valcore', image_name: '/wiki/Valcore', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Vampyr Mosp', image_name: '/wiki/Vampyr_Mosp', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wampus cat', image_name: '/wiki/Wampus_cat', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Water dragon parasite', image_name: '/wiki/Water_dragon_parasite', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Werewolf', image_name: '/wiki/Werewolf', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'White River Monster', image_name: '/wiki/White_River_Monster', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Winged horse', image_name: '/wiki/Winged_horse', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Abraxan Winged horse', image_name: '/wiki/Abraxan', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Aethonan Winged horse', image_name: '/wiki/Aethonan', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Granian Winged horse', image_name: '/wiki/Granian', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Thestral Winged horse', image_name: '/wiki/Thestral', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wyvern', image_name: '/wiki/Wyvern', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wyvern of Wye', image_name: '/wiki/Wyvern_of_Wye', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Yeti', image_name: '/wiki/Yeti', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Zouwu', image_name: '/wiki/Zouwu', real: 'Beasts', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant', image_name: '/wiki/Giant', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Goblin', image_name: '/wiki/Goblin', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dark Goblin', image_name: '/wiki/Dark_Goblin', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hag', image_name: '/wiki/Hag', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Half-breed', image_name: '/wiki/Half-breed', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Part elf', image_name: '/wiki/Part_elf', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Half-giant', image_name: '/wiki/Half-giant', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Half-goblin', image_name: '/wiki/Half-goblin', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Half-breed', image_name: '/wiki/Half-breed', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Part-vampire', image_name: '/wiki/Part-vampire', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Half-Veela', image_name: '/wiki/Half-Veela', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'House-Elf', image_name: '/wiki/House-Elf', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Yumbo House Elf', image_name: '/wiki/Yumbo', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Human', image_name: '/wiki/Human', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Maledictus', image_name: '/wiki/Maledictus', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Non-magic people', image_name: '/wiki/Non-magic_people', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Squib', image_name: '/wiki/Squib', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wizardkind', image_name: '/wiki/Wizardkind', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pukwudgie', image_name: '/wiki/Pukwudgie', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Troll', image_name: '/wiki/Troll', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Vampire', image_name: '/wiki/Vampire', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Veela', image_name: '/wiki/Veela', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Werewolf', image_name: '/wiki/Werewolf', real: 'Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Animal ghost', image_name: '/wiki/Animal_ghost', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ghost horse', image_name: '/wiki/Ghost_horse', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Banshee', image_name: '/wiki/Banshee', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ghost', image_name: '/wiki/Ghost', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Loose Hand', image_name: '/wiki/Loose_Hand', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gytrash', image_name: '/wiki/Gytrash', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Phantom Rat', image_name: '/wiki/Phantom_Rat', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant Phantom Rat', image_name: '/wiki/Giant_Phantom_Rat', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Spectre Bat', image_name: '/wiki/Spectre_Bat', real: 'Spirits', habitat: 'Harry Potter')
	Animal.create(search_name: 'Boggart', image_name: '/wiki/Boggart', real: 'Non-Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dementor', image_name: '/wiki/Dementor', real: 'Non-Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Poltergeist', image_name: '/wiki/Poltergeist', real: 'Non-Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Caipora', image_name: '/wiki/Caipora', real: 'Spirit-Beings', habitat: 'Harry Potter')
	Animal.create(search_name: 'Aquavirius Maggot', image_name: '/wiki/Aquavirius_Maggot', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Blibbering Humdinger', image_name: '/wiki/Blibbering_Humdinger', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Crumple-Horned Snorkack', image_name: '/wiki/Crumple-Horned_Snorkack', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dabberblimp', image_name: '/wiki/Dabberblimp', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Exploding Snabberwitch', image_name: '/wiki/Exploding_Snabberwitch', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gulping Plimpy', image_name: '/wiki/Gulping_Plimpy', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Heliopath', image_name: '/wiki/Heliopath', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hydra', image_name: '/wiki/Hydra', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Moon Frog', image_name: '/wiki/Moon_Frog', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Nargle', image_name: '/wiki/Nargle', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Skin-walker', image_name: '/wiki/Skin-walker', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Umgubular Slashkilter', image_name: '/wiki/Umgubular_Slashkilter', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Weetimorousbeastie', image_name: '/wiki/Weetimorousbeastie', real: 'Not_proven_real', habitat: 'Harry Potter')
	Animal.create(search_name: 'Abarimon', image_name: '/wiki/Abarimon', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Albino bloodhound', image_name: '/wiki/Albino_bloodhound', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Blood-Sucking Bugbear', image_name: '/wiki/Blood-Sucking_Bugbear', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Bogeyman', image_name: '/wiki/Bogeyman', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Cherub', image_name: '/wiki/Cherub', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Cobra Lily', image_name: '/wiki/Cobra_Lily', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Cockatrice', image_name: '/wiki/Cockatrice', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Crazed Capybara', image_name: '/wiki/Crazed_Capybara', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Curupira', image_name: '/wiki/Curupira', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dukuwaqa', image_name: '/wiki/Dukuwaqa', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dwarf', image_name: '/wiki/Dwarf', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fanged gerbil', image_name: '/wiki/Fanged_gerbil', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fire-breathing chicken', image_name: '/wiki/Fire-breathing_chicken', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flitterby', image_name: '/wiki/Flitterby', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Flying pig', image_name: '/wiki/Flying_pig', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Frog-Rabbit', image_name: '/wiki/Frog-Rabbit', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Genie', image_name: '/wiki/Genie', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant grub', image_name: '/wiki/Giant_grub', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Giant storm petrel', image_name: '/wiki/Giant_storm_petrel', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gigantic white worm', image_name: '/wiki/Gigantic_white_worm', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Gorgon', image_name: '/wiki/Gorgon', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Grim', image_name: '/wiki/Grim', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Harpy', image_name: '/wiki/Harpy', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Homo amphibia', image_name: '/wiki/Homo_amphibia', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Hydra', image_name: '/wiki/Hydra', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Inferius', image_name: '/wiki/Inferius', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Infant Demonic', image_name: '/wiki/Infant_Demonic', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Kraken', image_name: '/wiki/Kraken', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Marble Gargoyle (Trading Card)', image_name: '/wiki/Marble_Gargoyle_(Trading_Card)', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Michigan Dogman', image_name: '/wiki/Michigan_Dogman', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Mummy', image_name: '/wiki/Mummy', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Ogre', image_name: '/wiki/Ogre', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Poisonous duck', image_name: '/wiki/Poisonous_duck', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pukwudgie', image_name: '/wiki/Pukwudgie', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Purple Rabbit', image_name: '/wiki/Purple_Rabbit', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Rougarou', image_name: '/wiki/Rougarou', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sasabonsam', image_name: '/wiki/Sasabonsam', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sasquatch', image_name: '/wiki/Sasquatch', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sandstone Gargoyle', image_name: '/wiki/Sandstone_Gargoyle', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Sprite', image_name: '/wiki/Sprite', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wildflower sprite', image_name: '/wiki/Wildflower_sprite', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Transforming rabbit', image_name: '/wiki/Transforming_rabbit', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wood Nymph', image_name: '/wiki/Wood_Nymph', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wrackspurt', image_name: '/wiki/Wrackspurt', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Zombie', image_name: '/wiki/Zombie', real: 'Unknown_classification', habitat: 'Harry Potter')
	Animal.create(search_name: 'Bat', image_name: '/wiki/Bat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Fruit bat', image_name: '/wiki/Fruit_bat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Vampire bat', image_name: '/wiki/Vampire_bat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Cat', image_name: '/wiki/Cat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Chicken (animal)', image_name: '/wiki/Chicken_(animal)', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wild rooster', image_name: '/wiki/Wild_rooster', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Crow', image_name: '/wiki/Crow', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dog', image_name: '/wiki/Dog', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Dragonfly', image_name: '/wiki/Dragonfly', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Frog', image_name: '/wiki/Frog', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Green Tree Frog', image_name: '/wiki/Green_Tree_Frog', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Newt', image_name: '/wiki/Newt', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Owl', image_name: '/wiki/Owl', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Peacock', image_name: '/wiki/Peacock', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Albino peacock', image_name: '/wiki/Albino_peacock', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Pheasant', image_name: '/wiki/Pheasant', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Rat', image_name: '/wiki/Rat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Albino Rat', image_name: '/wiki/Albino_Rat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Black Rat', image_name: '/wiki/Black_Rat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Brown Rat', image_name: '/wiki/Brown_Rat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Grey Rat', image_name: '/wiki/Grey_Rat', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Rabbit', image_name: '/wiki/Rabbit', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Lop-Eared Rabbit', image_name: '/wiki/Lop-Eared_Rabbit', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wild Rabbit', image_name: '/wiki/Wild_Rabbit', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Raven', image_name: '/wiki/Raven', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Slug', image_name: '/wiki/Slug', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Snail', image_name: '/wiki/Snail', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Snake', image_name: '/wiki/Snake', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Boomslang', image_name: '/wiki/Boomslang', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Boa constrictor snake', image_name: '/wiki/Boa_constrictor', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Common adder snake', image_name: '/wiki/Common_adder', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Green snake', image_name: '/wiki/Green_snake', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Spider', image_name: '/wiki/Spider', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Black widow', image_name: '/wiki/Black_widow', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Brown Recluse', image_name: '/wiki/Brown_Recluse', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Funnelweb spider', image_name: '/wiki/Funnelweb_spider', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Redback spider', image_name: '/wiki/Redback_spider', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Tarantula', image_name: '/wiki/Tarantula', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Whitetail Spider', image_name: '/wiki/Whitetail_Spider', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Toad', image_name: '/wiki/Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Common Toad', image_name: '/wiki/Common_Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Crested Toad', image_name: '/wiki/Crested_Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Harlequin Toad', image_name: '/wiki/Harlequin_Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Horned toad', image_name: '/wiki/Horned_toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Natterjack Toad', image_name: '/wiki/Natterjack_Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Western Green Toad', image_name: '/wiki/Western_Green_Toad', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Tropical bird', image_name: '/wiki/Tropical_bird', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Wasp', image_name: '/wiki/Wasp', real: 'Magic_related_animals', habitat: 'Harry Potter')
	Animal.create(search_name: 'Tarantula hawk wasp', image_name: '/wiki/Tarantula_hawk', real: 'Magic_related_animals', habitat: 'Harry Potter')
  end
end
